### ISSUE TITLE
apply black/flake8

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-access-kit#111]

**Comment by cthoyt** [comment]
Assign me for this

**Comment by cmungall** [comment]
Thx! Lmk if you intend to make a big PR so we avoid conflicts

**Comment by matentzn** [comment]
Maybe better to go sub-module by sub-module.. One massive one will be very disruptive for a library with daily commits..

**Comment by matentzn** [comment]
Depends on how long you need :D This is hard work, no? Changing 1 million method signatures etc. In the end its your problem, lets say you work on the massive PR, then someone creates a new one in the meantime, no black validation there yet.. You know best man :) You have done it a bunch of times of us and I never looked back.

**Comment by cthoyt** [comment]
No, setting this up and running it takes less than 5 minutes, I already have the code ready, just need to pull the trigger.

**Comment by cthoyt** [comment]
just say when you want me to do it, I can right now
