### ISSUE TITLE
Force squash+merge for all commits

### ISSUE THREAD

**Issue by cthoyt** [INCATools/ontology-access-kit#121]
In order to keep the commit history focused on a high-level narrative, all pull requests should be done as squash + merge.

This can be enabled following this tutorial: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests.

1. Navigate to https://github.com/INCATools/ontology-access-kit/settings
2. Scroll down and turn off merge commits / rebase commits like below:

<img width="810" alt="Screen Shot 2022-06-17 at 12 10 12" src="https://user-images.githubusercontent.com/5069736/174277953-edc1b59a-0163-4104-97b4-45fd181727f2.png">

**Comment by cmungall** [comment]
I think this is done
