### ISSUE TITLE
add upper limit to trees in default --no-gap-fill mode

### ISSUE THREAD

**Issue by turbomam** [INCATools/ontology-access-kit#128]
I like `runoak tree`'s default `--no-gap-fill` mode (which _does_ fill in the gaps between my provided CURIEs, from my perspective)

_except_ it traverses all the way up to a root in the ontology. I would like a mode in which gaps between provided CURIEs are injected into the output, but no terms above the hierarchically highest term in the provided CURIEs injected.

FWIW, I'm just doing `--predicates i`

**Comment by turbomam** [comment]
Here's what I'm doing in a Makefile now. My colleagues have provided several EnvO terms that should be appropriate for annotating the environmental broad scale of biosample

It eliminates 
- terms that were already provided as input (`grep -v '\] \*\*`) 
  -  `runoak tree --no-gap-fill` already does that!
- many [terms above ENVO:00000428 'biome'](https://www.ebi.ac.uk/ols/ontologies/envo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FENVO_00000428) in EnvO's hierarchy
  - that's what I'm asking for
- any term whose label ends in 'environment' because we 

```shell
	runoak \
		--input sqlite:obo:envo tree \
		--predicates i \
		--no-gap-fill <provided EnvO CURIEs> \
		--output  artifacts/curated_soil_ebs_tree.txt
	cat artifacts/curated_soil_ebs_tree.txt | \
	grep -v '\] \*\*' | \
	grep -v 'BFO:0000001' | \
	grep -v 'BFO:0000002' | \
	grep -v 'BFO:0000004' | \
	grep -v 'BFO:0000040' | \
	grep -v 'ENVO:00000428' | \
	grep -v 'ENVO:01000254' | \
	grep -v 'ENVO:01001110' | \
	grep -v 'RO:0002577'  > artifacts/possible_additions.txt
```

**Comment by cmungall** [comment]
I think your use case is satisfied by running `--gap-fill`?

**Comment by turbomam** [comment]
> I think your use case is satisfied by running `--gap-fill`?

I don't think so. `--gap-fill` does the opposite if what I want. See https://github.com/microbiomedata/sheets_and_friends/blob/main/artifacts/curated_soil_ebs_tree.txt and https://github.com/microbiomedata/sheets_and_friends/blob/main/artifacts/gapfilled_curated_soil_ebs_tree.txt from https://github.com/microbiomedata/sheets_and_friends/blob/main/Makefile#L176-L198

I want the additional classes injected between my input but not any classes above the highest class in the input

**Comment by turbomam** [comment]
> Always include part-of with envo btw

I'm not convinced part-of helps in this case. It doubles the number of lines in the tree, but the only part-of relationships I see are above biome in the hierarchy, like

```
                        * [i] ENVO:01000799 ! astronomical body
                            * [p] ENVO:01000813 ! astronomical body part
```
