### ISSUE TITLE
Add parser for `.ttl`

### ISSUE THREAD

**Issue by joeflack4** [INCATools/ontology-access-kit#134]
## Summary
I'm trying to use OAK to search for terms using regular expressions. The file that I have is in RDF Turtle (`icd10cm.ttl`). But I ran into a parser error when I tried to do this.

## Python code
```python
from oaklib.resource import OntologyResource
from oaklib.implementations.pronto.pronto_implementation import ProntoImplementation
# ...
resource = OntologyResource(slug=onto_path, local=True)
oi = ProntoImplementation(resource)
# ...
search_results = []
for _index, row in df_regex.iterrows():
    regex_pattern = row['term_label'].replace('REGEX:', '')
    search_result = oi.basic_search(regex_pattern)  # <--- fails here
    search_results.append(search_result)
```

## Error message
The crux:
`ValueError: could not find a parser to parse '/path/to/icd10cm.ttl'`

Full error:
```
Traceback (most recent call last):
  File "/Users/joeflack4/virtualenvs/mondo-ingest/lib/python3.9/site-packages/pronto/ontology.py", line 286, in __init__
    raise ValueError(f"could not find a parser to parse {handle!r}")
ValueError: could not find a parser to parse '/Users/joeflack4/projects/mondo-ingest/src/scripts/exclusion_term_expansion/../../ontology/mirror/icd10cm.ttl'
```

## Things I tried
**Other implementations?**: I looked around to see if implementations other than `ProntoImplementation` had a parser for `.ttl`, but from what I could see, the only usage of `.ttl` in OAK is exporting in that format in some cases.

## Possible solutions
A. **Add `.ttl` parser**: It looks like a parser needs to be added for one of the implementations.

For my purposes for now, I could try and get a `.owl` version of `.ttl`. If one is not available, I imagine that there is some way to convert `.ttl` to `.owl` that I should know about. However, I don't know if these kinds of conversions are lossy at all, either. If they're not lossy, then that means there is also an alternative solution:

B. **Convert `.ttl`**: Can use some other library to convert `.ttl` to an OAK-parseable format like, and then parse that.

## Additional information
The GitHub issue that I'm working on where I'm experiencing this problem: https://github.com/monarch-initiative/mondo-ingest/issues/22

**Comment by matentzn** [comment]
Thanks a ton @joeflack4 to working with OAK. This will make our lives much easier over time.

Just use another Ontology Parser for now, not pronto (you can use rdflib which covers ttl). For speed, this is the recommended process (hit @hrshdhgd for details):

1. Use semanticsql to turn your ontology into sqlite (.db file)
2. load .db using the SqliteImpl()

**Comment by joeflack4** [comment]
Awesome recommendations guys, thanks.

@cmungall Just a comment on UX. This is something I felt when I first used OAK, and probably will feel this way for awhile. Maybe it's just because I don't have a formal background in this stuff. But while I understand the purposes of implementations, I really like when libraries "just work". It would be nice to have a **(a)** default implementation, and a user can use OAK without even thinking / knowing about these implementations. Or **(b)** They could instantiate a resource object, and then maybe make method calls directly on that. I suppose both (a) and (b) under the hood would take a method call and then route to a pre-determined "best" default implementation to use for that call.
