### ISSUE TITLE
what do the symbols in trees mean?

### ISSUE THREAD

**Issue by turbomam** [INCATools/ontology-access-kit#137]
I think some of this is already documented somewhere

- `**`: a term explicitly provided in the input
- `[X]`: the term on this line is related to the term on one line up by predicate X, like `is_a` or `part_of`
  - those are documented somewhere now too, right?
- what does the initial `*` mean?
- why are term IDs and labels separated with an exclamation mark `!` instead of a pipe `|`
  - _OK, that's not really an issue_

**Comment by cmungall** [comment]
> **: a term explicitly provided in the input

Yes, this is markdown bold highlighting; e.g.

`pato tree shape`

generates:

* [] BFO:0000002 ! continuant
    * [i] BFO:0000020 ! specifically dependent continuant
        * [i] PATO:0000001 ! quality
            * [i] PATO:0001241 ! physical object quality
                * [i] PATO:0000051 ! morphology
                    * [i] **PATO:0000052 ! shape**

All tree/graph displays by default will highlight the seed terms

Currently `tree` doesn't accept kgviz stylesheets like `viz` does,  but it will in future, and all this will be highly customizable, different terminal colors for different ontologies, etc

For more on ontology visualization stylesheets:

https://github.com/INCATools/obographviz#stylesheet-standard

> [X]: the term on this line is related to the term on one line up by predicate X, like is_a or part_of
> those are documented somewhere now too, right?

FAQ:

https://incatools.github.io/ontology-access-kit/faq.html#command-line

Tutorial:

https://incatools.github.io/ontology-access-kit/intro/tutorial01.html#predicate-abbreviations

Command lines docs:

https://incatools.github.io/ontology-access-kit/cli.html#predicates

This is standard convention, bioportal and OLS all use "p" for part-of. This is often unusual to folks coming from OWL where existential restrictions are routinely ignored, but is standard for GO, anatomy ontologies + CL, ENVO, etc where part-of is as important if not more important than is-a

E.g

<img width="561" alt="image" src="https://user-images.githubusercontent.com/50745/175441259-339d114f-ffc1-4723-9413-f5ba057a7969.png">


> what does the initial * mean?

This is just markdown list syntax

The different output formats need proper docs and enumization but for now, you with tree you can select between markdown (default) and text

```
pato tree shape -O txt
```

```
* [] BFO:0000002 ! continuant
.* [i] BFO:0000020 ! specifically dependent continuant
..* [i] PATO:0000001 ! quality
...* [i] PATO:0001241 ! physical object quality
....* [i] PATO:0000051 ! morphology
.....* [i] **PATO:0000052 ! shape**
```

doesn't really offer so many advantages over the markdown so we may as well keep md as default

> why are term IDs and labels separated with an exclamation mark ! instead of a pipe |

This convention comes from oboformat, we can make this configurable
