### ISSUE TITLE
Reduce `print()` calls in tests

### ISSUE THREAD

**Issue by cthoyt** [INCATools/ontology-access-kit#173]
Right now it's pretty difficult to run the tests since they create such a huge amount of output. Ideally, the print statements in tests can be switched to using the logger module, then the test harness only shows the results from failed tests.

**Comment by pkalita-lbl** [comment]
I think this can be closed now that #210 is merged. @cthoyt had some good follow-on tasks in the comments of that PR. I can make issues for those.
