### ISSUE TITLE
Improving lexmatch docs

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-access-kit#192]
Looking at https://incatools.github.io/ontology-access-kit/cli.html#cmdoption-runoak-lexmatch-L,

- [ ] Add extended documentation of the -L parameter, at least one sentence of what a lexical index file is or where you can learn more.
- [ ] Add a sentence to the docs of the -R parameter, provide a link to where you can learn more about the rule file metadata (maybe examples)
- [ ] --add-labels, explain a tiny bit better what this does, maybe an example.
- [ ] One thing that would be great if we could wrap standard matches like AML and LogMatch in the lexmatch interfaces. Even if it does not turn out feasible right now, we should make sure it is possible in the future, much the same way as we wrap ROBOT for various tasks. I have code to harmonise the outputs of these matches to sssom. These should probably be implemented as a module, and the OAK matcher be conceptualised as a reference implementation. For now, lets just create a page somewhere in the docs "How to extend the `lexmatch` interfaces to implement alternative matchers - this will help us ensure it is at all possibel.
- [ ] From the CLI docs of lexmatch, add see also links to the actual library interfaces

**Comment by cmungall** [comment]
For AML/LogMatch etc, see https://incatools.github.io/ontology-access-kit/howtos/write-a-plugin.html and also #171

**Comment by cmungall** [comment]
For CLI docs, I had been experimenting with using rst syntax but I don't think that's a good idea. Just use plain URLs. Works better with `--help` and in the CLI notebook the URL will show up hyperlinked:

https://github.com/INCATools/ontology-access-kit/blob/main/notebooks/Command-Line-Examples.ipynb

<img width="828" alt="image" src="https://user-images.githubusercontent.com/50745/179834679-93e29662-4550-4ff9-8803-7e9d65aa5c6d.png">
