### ISSUE TITLE
CLI: SSSOM ImportError

### ISSUE THREAD

**Issue by joeflack4** [INCATools/ontology-access-kit#211]
## Summary
I have a list of terms and I'm trying to get their labels using the OAK CLI, but I got errors.

### `labels` CLI option
https://incatools.github.io/ontology-access-kit/cli.html#runoak-labels
**Command**: `runoak -i mirror/icd10cm.ttl labels .all`
**Short err**: `ImportError: cannot import name 'LICENSE' from 'sssom.constants'`
**Long err**:
```
Traceback (most recent call last):
  File "/Users/joeflack4/virtualenvs/mondo-ingest/bin/runoak", line 5, in <module>
    from oaklib.cli import main
  File "/Users/joeflack4/virtualenvs/mondo-ingest/lib/python3.9/site-packages/oaklib/[cli.py](http://cli.py/)", line 99, in <module>
    from oaklib.utilities.lexical.lexical_indexer import (
  File "/Users/joeflack4/virtualenvs/mondo-ingest/lib/python3.9/site-packages/oaklib/utilities/lexical/[lexical_indexer.py](http://lexical_indexer.py/)", line 16, in <module>
    from sssom.constants import LICENSE, MAPPING_SET_ID
ImportError: cannot import name 'LICENSE' from 'sssom.constants' (/Users/joeflack4/virtualenvs/mondo-ingest/lib/python3.9/site-packages/sssom/[constants.py](http://constants.py/))
```

### `fill-table` CLI option
https://incatools.github.io/ontology-access-kit/cli.html#runoak-fill-table
**Command**: `runoak -i mirror/icd10cm.ttl fill-table ~/Desktop/my-table.tsv`
**Short err**: `ImportError: cannot import name 'LICENSE' from 'sssom.constants'`
**Long err**: _(see above; same error)_

## Additional information
Relevant dependency versions:
```
oaklib==0.1.34
sssom==0.3.11
sssom-schema==0.9.4
```
All dependency versions: [mondo-ingest-pip-freeze.txt](https://github.com/INCATools/ontology-access-kit/files/9194496/mondo-ingest-pip-freeze.txt)

**Comment by hrshdhgd** [comment]
@joeflack4 , run `poetry update` and then re-run the above commands. These work fine on my side. My guess is the old version `sssom` (v0.3.11) is the cause of this issue here.

**Comment by joeflack4** [comment]
Looks like it's fixed now!

I don't know if `poetry update` would help in the CLI context. What I meant to imply as well by this being a CLI problem is that this issue should also apply to a global installation of `oaklib`. So if I am just fresh installing `oaklib` globally on my machine, the CLI should be able to work without me needing to install another package manager or any other packages. Either way, I installed the latest version of `oaklib` globally and it's all good now!
