### ISSUE TITLE
`curie_from_iri()` issues

### ISSUE THREAD

**Issue by joeflack4** [INCATools/ontology-access-kit#214]
## Overview
I know that we are moving to OAK, but I've been having a lot of trouble getting my OAK use cases to work so far, and [@matentzn  recommended](https://github.com/monarch-initiative/mondo-ingest/pull/35#discussion_r918476599) that I tried the `bioregistry` function first. However I had problems w/ that, so I opened up 2 issues: (https://github.com/biopragmatics/bioregistry/issues/479, https://github.com/biopragmatics/bioregistry/issues/480)

I then went on to use OAK, but had some issues here as well.

### 1. Fails when angle brackets present in URI
I don't have a code snippet for this, sorry. But I did not get the correct result.

### 2. Duplicated code
This may not be comprehensive, but I see the same block of code for this in `BasicOntologyInterface`, `FunOwlImplementation`, and `AbstractSparqlImplementation`.

### 3. No static function
It shouldn't be necessary to load up an ontology instantiate an implementation / interface object. If I have a single URI string, and a `prefix_map`, I should be able to use OAK in a simple way by using 1 line of code to import the `uri_to_curie` and a second line to call the function.

There should probably be some area in OAK to store such static functions. Then, the classes can wrap around that; something like:
```py
from oaklib.utils import uri_to_curie

def uri_to_curie(self, uri: URI, strict=True) -> Optional[CURIE]:
    pm = self.get_prefix_map()
    return uri_to_curie(uri, pm)
```

Better yet, put it in `OntologyInterface` (assuming all the implementation / interfaces in inherit from that) and even that wrapper method needs only be declared once.

**Comment by matentzn** [comment]
> 1. Fails when angle brackets present in URI

Is not a problem - ankle brackets simply means that the IRI was not formed correctly (see my comments on Mondo ingest PR)

Agree with all the rest. Thanks for making the issue!

**Comment by joeflack4** [comment]
Meh. I know what you guys mean. I'm honestly fine if you guys don't want to add this but if I was writing a library that was meant to be used with these kind of technologies, given how often I see the brackets present in the URLs, I would just add the parsing for convenience.

**Comment by matentzn** [comment]
I think the amount of failure this will introduce will be staggering.. If we start allowing `<URI>` for this function, we will have to consider it for other ones - and then we start creating a real potential timebomb (we suggest to our users `<URI>` is ok, but some function somewhere in the stack does not deal with it correctly.. No, I am pretty sure that `<` are not allowed characters in URL, and we should fail hard we when see them to give clients a chance to fix their code..

**Comment by joeflack4** [comment]
I hear you, it's not really a URI when it's in the brackets. It's just a URI ref string that appears a lot. Probably can be fixed upstream.

**Comment by joeflack4** [comment]
We could also as another option use Charlie's new utility https://github.com/cthoyt/curies, but perhaps that is DRYify'ing things too much.

**Comment by cmungall** [comment]
That's a great idea @joeflack4 - I haven't looked at this new library yet, but we should use it or the bioregistry package

And yes, just to confirm, the expected input for this function is the URI itself, *not* for `<URI>`
