### ISSUE TITLE
Create OAK logo

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-access-kit#222]

**Comment by jmcmurry** [comment]
<img width="351" alt="image" src="https://user-images.githubusercontent.com/3658863/183826599-912c7eee-8845-4e44-9e3b-114c3842e52f.png">

drafts

**Comment by matentzn** [comment]
Hey Julie, here some ideas based on your suggestions. If the tree (E) would have roots instead of being mirrored, and these roots are graph nodes, than the concept that oak facilitates access to the "hidden semantic layer" could be illustrated. Just an idea

**Comment by cthoyt** [comment]
I like E

**Comment by nlharris** [comment]
I like Nico's idea about how to modify E!

**Comment by cmungall** [comment]
Agreed!

**Comment by joeflack4** [comment]
Those are stellar. I think E is the coolest, as well.

I like to fiddle around with Dall-E, and here's some things I got while just spit-balling.

<img width="1701" alt="Screen Shot 2022-08-25 at 4 59 35 PM" src="https://user-images.githubusercontent.com/13045020/186767919-ae83be84-7c78-4e24-8bd5-869d5776c385.png">
<img width="536" alt="Screen Shot 2022-08-25 at 5 02 25 PM" src="https://user-images.githubusercontent.com/13045020/186768353-db56f837-aac9-445e-bced-5eeee17639ef.png">
<img width="486" alt="Screen Shot 2022-08-25 at 5 02 44 PM" src="https://user-images.githubusercontent.com/13045020/186768357-d769c39a-2dd3-42ae-9718-512e6606c42e.png">

**Comment by jmcmurry** [comment]
Here are the E variants per request: 
![image](https://user-images.githubusercontent.com/3658863/215376075-f8c0633c-1a8b-480c-8660-c40ae869c312.png)

**Comment by nlharris** [comment]
Ooh, I love them alllll! I guess I'm going to vote for E3, because it has the most legible OAK and graph-y roots. (In fact, OAK could be even bigger if you dropped it a little lower where there's more space!)

**Comment by matentzn** [comment]
I also Love them all. I think e2 is best, closely followed by e3, but I can get behind all of them.

**Comment by caufieldjh** [comment]
I really like the more stylized ones, like E1 and E5, but they're all fantastic.

**Comment by matentzn** [comment]
>  Do you like some of the roots ending in "nodes" and some not?

Didnt even notice, I don't mind!

**Comment by jmcmurry** [comment]
here's e2 with a bit more legibility and playing with slight stylization
<img width="754" alt="image" src="https://user-images.githubusercontent.com/3658863/215568051-e16d0009-8ff9-4e9a-beec-e6d410c5dd28.png">

**Comment by nlharris** [comment]
Haha, I love how the version of the logo are branching.

I like E2b the best, but am intrigued by the node-y approach to OAK in c, which could be good as a standalone icon for when the tree is too much.

**Comment by jmcmurry** [comment]
I don't think a standalone of stylized oak would work without the tree. I'll wait on more votes before doing the last push with the frontrunner of these.

**Comment by nlharris** [comment]
Does anyone want to vote for E2a or E2c over my choice of E2b? (I'm fine with all of them!)

**Comment by matentzn** [comment]
i like them all, tending to a>b>c, `a` being 1 thousandth of a taste-millimeter  better

**Comment by jmcmurry** [comment]
Coming back to it fresh, I also prefer E2a. I'll go ahead and push that forward given it doesn't seem like strong feelings abound after 2 weeks.

**Comment by jmcmurry** [comment]
I went to invert this (per usual variations) and didn't like how subtle and detailed the roots were. I realized that at the sizes logos are normally used, this is going to look messy; for this reason I think E2a is out. I also didn't like how stark the horizon was. Ergo, I made two alternatives. Honestly, after all this, I prefer E2e as it is bold and simple yet somehow pleasing. I could be persuaded to use E2d if enough people prefer it.

<img width="700" alt="image" src="https://user-images.githubusercontent.com/3658863/218382112-a9bd3dfb-10ce-47f1-b6b7-092fd7dca3d2.png">

**Comment by nlharris** [comment]
So E2e won't say oak or OAK on it?

**Comment by jmcmurry** [comment]
When it is an icon mode, we would, but not when it is in banner mode

**Comment by jmcmurry** [comment]
(similar to what we did for odk)

**Comment by jmcmurry** [comment]
like so

<img width="850" alt="image" src="https://user-images.githubusercontent.com/3658863/218391680-974c581c-bf61-4278-b927-d635d941b859.png">

**Comment by matentzn** [comment]
This looks beautiful, not saying - but from a purely ideological perspective I really like the roots with the nodes - if you want to simplify that much, would it be possible to get at least a few of these "graph roots" back in the picture?

**Comment by jmcmurry** [comment]
TBH, I still really prefer the starkness of the no roots version but I could live with something along these lines. In order of my preference, the options are:

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/3658863/220031012-3ce08bcc-c71f-4bd8-bb92-d448c7e6d33d.png">

I played with a bunch of others and strongly dislike them because they break with the style of the top and diminish its prominence.
 
<img width="963" alt="image" src="https://user-images.githubusercontent.com/3658863/220029555-2db7f151-60db-4db6-bad4-b9e2632c05b0.png">

**Comment by matentzn** [comment]
You put a lot of energy into this logo, thank you very much :) I hope we can promote OAK to be worthy of your logo efforts!

I will let others decide! I don't really come from it from an aesthetic perspective, but from one of semantics - the graph-node roots are where the OAK draws its energy from to create the strong trunk. From an aesthetic perspective I don't know!

**Comment by caufieldjh** [comment]
The contrast in the root-free versions is really satisfying. If the roots must be present then my preference is for option A above.

**Comment by jmcmurry** [comment]
Here's another compromise to get at the fact that the tool works above and below the waterline so to speak. 
<img width="748" alt="image" src="https://user-images.githubusercontent.com/3658863/220419517-cef5b866-e278-4df9-9892-d8fa397f316b.png">

**Comment by matentzn** [comment]
Nice! I like that!

**Comment by jmcmurry** [comment]
I pinged @mellybelly says she loves it, and let's be done.

**Comment by jmcmurry** [comment]
Here you go, https://github.com/jmcmurry/closed-illustrations/tree/master/logos/oak-logos thanks everyone for your input. I think we landed at a happy compromise
