### ISSUE TITLE
`ProntoImplementation.label()`: Not yielding results for some ontologies

### ISSUE THREAD

**Issue by joeflack4** [INCATools/ontology-access-kit#276]
## Overview
I'm trying to get labels from term CURIEs for the following ontologies: OMIM, ORDO, ICD10CM, ICD10WHO, NCIT, DOID. Of these, DOID and NCIT are returning labels for 100% of terms. But I'm getting no labels back for the other ontologies.

## Replicating the issue
This work is currently being done on the [`slurpdraft` branch of `mondo-ingest`](https://github.com/monarch-initiative/mondo-ingest/tree/slurpdraft). Sorry for not pasting a code snippet here. The best way to try and replicate the issue is to: 
1. Clone/update `mondo-ingest`
2. Check out the `slurpdraft` branch
3. Ensure docker is running in the background and `odkfull` is loaded and up-to-date.
4.a. Using ODK and no debugging: From `src/ontology/`, run `sh run.sh make slurp-all` to run all ontologies, or `sh run.sh make slurp-%` to run `%` ontology, replacing `%` with one of: `omim`, `ordo`, `icd10cm`, `icd10who`, `ncit`, or `doid`.
4.b. Using debugging: Probably a good idea to still run the previous command for an ontology in order to download and make all the prerequisites. Then, you can load an IDE, [set a breakpoint here](https://github.com/monarch-initiative/mondo-ingest/blob/slurpdraft/src/scripts/migrate_utils.py#L121), and, from `src/ontology/`, run the `src/scripts/migrate.py`, passing the following params (e.g. for `omim`): `--ontology-path components/omim.owl --sssom-map-path tmp/mondo.sssom.tsv --min-id 123000 --mondo-terms-path reports/mirror_signature-mondo.tsv --onto-config-path metadata/omim.yml --outpath slurp/omim.tsv`

## Additional information
I checked to see how labels are defined in these ontologies. For the ones that succeeded, I could see that `rdfs:label` was defined directly on classes for success case DOID, and I don't think annotations had labels. For success case NCIT, it looked like `rdfs:label` was on both annotations and classes. For non-success cases OMIM, ORDO, ICD10CM, and ICD10WHO, `rdfs:label` was on a mix of classes and annotations.

**Comment by matentzn** [comment]
Would it be possible to develop a small ontology (a single class from OMIM) that replicates the issue, and a CLI command example that illustrates the failure. Instructing anyone to clone mondo-ingest will mean that no one will deal with this ticket..  :P Sorry about the extra work!

**Comment by joeflack4** [comment]
For some reason this issue is not happening now. Wish I knew why it's good now. I didn't change any code since, or update any python packages I don't think. Oh well. @matentzn FYI
