### ISSUE TITLE
Viz command always attempts to display image even when --output is passed

### ISSUE THREAD

**Issue by hrshdhgd** [INCATools/ontology-access-kit#277]
The OAK generates a graphviz png, and then uses the system “open” command to display it. There is no way to mask the “open” system command, even when `--output` is passed. This prohibits its use in batch modes or pipelines.
 

> Example:
> We are using `obographviz` within an ODK Docker container with the [Makefile here](https://github.com/monarch-initiative/mondo/blob/033a9339afa7e7eb7b5d9dae289a79783bc738cc/src/ontology/mondo.Makefile#L720). The process runs perfectly and the image is generated. But after the image generation an error is thrown:
> ```
> Traceback (most recent call last):
>   File "/usr/local/bin/runoak", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/oaklib/cli.py", line 1091, in viz
>     subprocess.run(["open", imgfile])
>   File "/usr/lib/python3.10/subprocess.py", line 501, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'open'
> ```
> 
> This is because it is trying to open the png file located within the Docker image and cannot find it. Any suggestions as to how to handle it?

**Comment by gouttegd** [comment]
Calling `runoak viz` with the `--no-view` option? It’s supposed to prevent the program from trying to open an image viewer to view the generated file. Such an option should always be used whenever you use `runoak` in a Docker container, as there’s no way to display something from within a container AFAIK.

**Comment by hrshdhgd** [comment]
Thanks @gouttegd !! That did the trick
