### ISSUE TITLE
Bug: `RecursionError`: `SqlImplementation.outgoing_relationships()`

### ISSUE THREAD

**Issue by joeflack4** [INCATools/ontology-access-kit#290]
## Overview
When trying to get parents / relationships of a term, I get a `RecursionError`

## Error message
Short err:
> `RecursionError: maximum recursion depth exceeded while calling a Python object`

Long err (truncated):
```
...
 File ".../oaklib/interfaces/basic_ontology_interface.py", line 524, in outgoing_relationships
    for p, vs in self.outgoing_relationship_map(curie).items():
  File ".../oaklib/implementations/sqldb/sql_implementation.py", line 477, in outgoing_relationship_map
    return pairs_as_dict(self.outgoing_relationships(*args, **kwargs))
  File ".../oaklib/utilities/basic_utils.py", line 15, in pairs_as_dict
    for p in pairs:
  File ".../oaklib/interfaces/basic_ontology_interface.py", line 524, in outgoing_relationships
    for p, vs in self.outgoing_relationship_map(curie).items():
  File ".../oaklib/implementations/sqldb/sql_implementation.py", line 476, in outgoing_relationship_map
    def outgoing_relationship_map(self, *args, **kwargs) -> RELATIONSHIP_MAP:
RecursionError: maximum recursion depth exceeded while calling a Python object
```

## Replicability
```py
from oaklib import OntologyResource
from oaklib.implementations import SqlImplementation
ontology_path = 'ordo.owl'
sql_ontology = SqlImplementation(OntologyResource(slug=ontology_path, local=True))  # ~17 sec
sql_ontology.outgoing_relationship_map('Orphanet:101334')
```

## Observations
I checked the debugger, and I put the values of what the params resolved to in comments.

1. The call
```py
sql_ontology.outgoing_relationship_map('Orphanet:101334')
```
2. `outgoing_relationship_map()` -> `outgoing_relationships()`
```py
    def outgoing_relationship_map(self, *args, **kwargs) -> RELATIONSHIP_MAP:
        # args: tuple('Orphanet:101334')
        # kwargs: {}
        return pairs_as_dict(self.outgoing_relationships(*args, **kwargs))  # <----- goes to step (3)
```
3. `outgoing_relationships()` -> `outgoing_relationship_map()`
```py
    # curie: 'Orphanet:101334'
    # predicates: None
    def outgoing_relationships(self, curie, predicates):
        for p, vs in self.outgoing_relationship_map(curie).items():  # <----- goes to step (2)
            if predicates is not None and p not in predicates:
                continue
            for v in vs:
                yield p, v
```

## Possible solutions
I haven't looked at this too closely, but I don't think this is simply that there is such a large tree of resolution such that the recursion limit (1,000 by default in Python, I think) is exceeded. For each one of the calls in step (2) and (3), the params are the same (just `'Orphanet:101334'`), so I think this is just a straight bug resulting in an infinite call loop.

**Comment by cmungall** [comment]
hmm, this is odd, there is no intention to use recursion here, this just looks like a mistake in terms of which method should be primary and which one is derived. Regardless of any tree depth, if the call tree is a cycle we'll always get recursion. But test_relationships in test_sqldb should catch this. Can you try running that test? And just confirm are you using main, or a specific pypi release?

You you also confirm what file code block 3 is in?

In we look at the pair of calls in sql_implementation there is no reciprocal calls:

https://github.com/INCATools/ontology-access-kit/blob/d181130e2232a919aecdf1007f2677453171ce4b/src/oaklib/implementations/sqldb/sql_implementation.py#L460-L491

**Comment by joeflack4** [comment]
> Can you try running that test?
Bit strapped for time today and tomorrow, but can try to find time next week.

> You you also confirm what file code block 3 is in?
Stack trace shows `basic_ontology_interface.py`:  `File ".../oaklib/interfaces/basic_ontology_interface.py", line 524, in outgoing_relationships`

> And just confirm are you using main, or a specific pypi release?
I was using `1.41`. I just switched to the latest, `1.43`, but but got: `sqlite3.OperationalError: no such table: edge`

Wasn't expecting that. This is the same error I got when trying to run some of the other methods: https://github.com/monarch-initiative/mondo-ingest/pull/36#discussion_r978195533

```
make: Nothing to be done for `ordo.db'.
Traceback (most recent call last):
  File "/Users/joeflack4/virtualenvs/mondo-ingest/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/Users/joeflack4/virtualenvs/mondo-ingest/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: edge
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/joeflack4/virtualenvs/mondo-ingest/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/joeflack4/virtualenvs/mondo-ingest/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/Users/joeflack4/virtualenvs/mondo-ingest/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/joeflack4/virtualenvs/mondo-ingest/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/Users/joeflack4/virtualenvs/mondo-ingest/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: edge
[SQL: SELECT edge.subject AS edge_subject, edge.predicate AS edge_predicate, edge.object AS edge_object 
FROM edge 
WHERE edge.subject = ?]
[parameters: ('Orphanet:101334',)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
python-BaseException
```

Note that I didn't pre-make SQLite DB, but from what I've heard, that's just an extra step I could take beforehand in order to speed things up.

In any case, it looks like moving from `1.41` to `1.43` resolved the issue. I often forget to `--upgrade` regularly / when I get an issue, sorry.

I was planning on making an issue next week concerning the `sqlite3.OperationalError: no such table: edge`, but maybe that's something we can look into here as well. Or I could close and reopen a new issue.

**Comment by cmungall** [comment]
The best way to debug this is

```
sqlite3 ordo.db
select * from edge limit 5
```

I am guessing something happened when building ordo.db

It may be the case that ordo.db doesn't even exist on the path you specify. sqlite will happily allow you to "connect" to an empty file and only barf when you query a table. We should but in some kind of check for that

**Comment by joeflack4** [comment]
Thanks, Chris.

I'm not surprised to see this result, given the Python error message.
```
sqlite3 ordo.db
SQLite version 3.28.0 2019-04-16 19:49:53
Enter ".help" for usage hints.
sqlite> select * from edge limit 5;
Error: no such table: edge
```

You're right. It does exist, but it is empty:
```
file ordo.db
ordo.db: empty
```

```
ls -l | grep ordo.db
-rw-r--r--   1 joeflack4  staff      0 Sep 22 20:57 ordo.db
```

---

Just a reminder how I'm loading using `SqlImplementation`. I'm just doing:
```
from oaklib.implementations import SqlImplementation
ontology_path = 'ordo.owl'
sql_ontology = SqlImplementation(OntologyResource(slug=ontology_path, local=True))
```

The next time I work on something that will require OAK, I can try and make the DB manually beforehand (I think I have some notes somewhere on how to do that), but it would make me very happy to do it this simpler way.

**Comment by joeflack4** [comment]
Closing this issue since the `RecursionError` is gone after I upgraded. I linked this issue to #90 . That is the core issue that is still the problem.
