### ISSUE TITLE
`fill-table` should respect commented rows

### ISSUE THREAD

**Issue by hrshdhgd** [INCATools/ontology-access-kit#313]
I'm passing a SSSOM tsv file as a table to be filled for a resource (owl, obo or db file). It works fine when I remove the `metadata` and `prefix_map` from the file and just pass the `dataframe` part of the tsv file. When I pass the tsv as is i.e. `metadata` + `prefix_map` + `dataframe`, it gets stuck while parsing the column names of the `dataframe` (which is parsed as a list) and says it expects a string.

e.g.
when I run this in MONDO:
```runoak -i tmp/mondo-ingest.db fill-table tmp/mondo.sssom.tsv  ```

it throws, 
```
../oaklib/utilities/table_filler.py", line 126, in parse_table
    m = LIST_PATTERN.match(v)
TypeError: expected string or bytes-like object
```

See https://github.com/monarch-initiative/mondo/pull/5491 and also https://github.com/monarch-initiative/mondo/issues/5329#issuecomment-1275384941

cc: @matentzn

**Comment by matentzn** [comment]
It's a tough case to generalize but my take is that header rows (until the first non commented row) should be skipped before filling, and then flushed back out where they were.

**Comment by cmungall** [comment]
Agreed.

As I see it there are layered standards with varying degrees of adoption

1. base level: TSVs (in fact pretty poor standardization here)
2. well-behaved TSVs: unicode, unix CRs, column headers
3. TSVs with comment block, using `#` as marker at start of line
4. comment blocks having well formed yaml
5. yaml blocks conforming to yaml-ld, including prefixmaps
6. multiple domain formats like sssom

A generic command like fill-table:

- must assume at least level 2
- allows for level 3, with option to switch off (e.g. if col1 really does start with a hash)
- in future support for 5, to retrieve non-standard prefixmaps (but non-standard prefix maps can always be passed on a CLI for now)
