### ISSUE TITLE
Can't seem to dump an obograph from an `.owl` file

### ISSUE THREAD

**Issue by joeflack4** [INCATools/ontology-access-kit#321]
## Overview
I have an `.owl` file, and I want to create an Obograph, either as a Python dictionary, or a JSON string. I tried the following things, but couldn't get them to work.

```python
    from oaklib.interfaces.obograph_interface import OboGraphInterface
    from oaklib import OntologyResource
    inpath = 'path/to/mondo.owl'
    r = OntologyResource(slug=inpath)
    x = OboGraphInterface(r)  # loads an object, but not the obograph itself (until I do use some method)
    x2 = x.as_obograph()  # NotImplementedError
    x3 = x.load_graph()  # NotImplementedError
    x4 = [x for x in x.nodes()]  # NotImplementedError
```

## Additional information
I looked at the [docs](https://incatools.github.io/ontology-access-kit/interfaces/obograph.html) and also looked through the code for `interfaces.obograph_interface` and `datamodels.obograph`, but could not find a method to use to load an obograph from an `.owl` file, or any other combination of methods that I could use to achieve this.

**Comment by joeflack4** [comment]
Oops. I know what an interface is. Seems silly that I reached for one again for functionality. I think I figured that what I needed in order to get an obograph was on the ppage you linked](https://incatools.github.io/ontology-access-kit/interfaces/obograph.html). But in hindsight, looking back a the [docs](https://incatools.github.io/ontology-access-kit/interfaces/obograph.html), or if I just thought about the codebase for a second, it seems implicit and obvious that I should use one of the implementations. Not sure why I was just looking for files named "obographs". I could've just looked did a text search to see which implementations do implement obograph methods. I'll see if I can give this a go tomorrow.

**Comment by cmungall** [comment]
yes the existing obograph_implementation is easily confused with the interface, perhaps it should be called obograph_direct_implementation, or obograph_in_memory_implementation, to capture the fact this implementation works by directly accessing an obograph object.
