### ISSUE TITLE
`oaklib:cli.annotate()` may need some redesign.

### ISSUE THREAD

**Issue by hrshdhgd** [INCATools/ontology-access-kit#329]
Currently the `annotate` command in the presence of a `--text-file`, iterates through each line and then passes the line to the implementation layer to annotate which in turn `return`s or `yield`s a result.

In your use case for `oakx-oger` , OGER takes input files (various formats) as a whole and spits out output(s) accordingly. OGER does not seem to have a functionality where you pass a word and it gives back its annotation.

Options to address this:

- There could be a flag that indicates if the `--text-file` is passed on to the implementation and let it handle the reading and processing? [default = False]
- (I don't like this) There be an `if` check for `OGERImplementation` which decides to pass the `--text-file` as a param to the `annotate_text()` in `oger_implementation.py`.

any other ideas @cmungall ?

**Comment by cmungall** [comment]
- Add a new method `annotated_text()` with same arguments (other than first) to `annotate` in the interface
 - default implementation should be to read file line by line and pass inputs to `annotate`
 - oger_implementation will override this; this will be the main method
 - oger_implementation will also provide an implementation of `annotate()` that creates a temp file and passes that to oger
