### ISSUE TITLE
Unable to find current curie from alt_id

### ISSUE THREAD

**Issue by yaseminbridges** [INCATools/ontology-access-kit#340]
```
[Term]
id: HP:0030051
name: Tip-toe gait
alt_id: HP:0002394
alt_id: HP:0040083
def: "An abnormal gait pattern characterized by the failure of the heel to contact the floor at the onset of stance during gait." [PMID:24757457, PMID:26709689]
comment: Tip-toe walking (or simply toe-walking) is common in healthy young children, and should resolve spontaneously by 3 years of age. After this age, tip-toe gait must be differentiated from habitual toe gait, congenital short tendo calcaneus, cerebral palsy, syringomyelia, spinal tumor, hematoma in a lower limb muscle, or neuromuscular diseases like muscular dystrophy, Charcot-Marie-Tooth disease and hereditary sensorimotor neuropathies. If the toe gait persists for 2-3 years, this gait pattern is not considered to be habitual. Therefore, the judgment of habitual toe gait should not be determined without evaluation for other diseases.
synonym: "Tiptoe gait" EXACT []
synonym: "Toe walking" EXACT layperson []
synonym: "Walking on tiptoes" EXACT layperson []
xref: UMLS:C1843570
is_a: HP:0001288 ! Gait disturbance
```

I'm looking at the alt_id HP:0040083 and I am looking to access the parent term for it, however, as it is an alt_id OAK doesn't retrieve a parent term. I wondered if there is a way to retrieve the current term from the alt_id.

**Comment by matentzn** [comment]
`alt_id` is a weak spot of OBO format. Conceptually, these are considered "deprecated" and should not be used in data curation at all. So 

```
[Term]
id: HP:0030051
alt_id: HP:0040083
```

should really be replaced by:

```
[Term]
id: HP:0030051

[Term]
id: HP:0040083
replaced_by: HP:0030051
```

**Comment by julesjacobsen** [comment]
@matentzn so is this going to happen in HPO? Even so, it doesn't really solve our immediate problem as OAK simply doesn't parse or return the data we need to be able to replace deprecated terms by their current term. @yaseminbridges will add this data to the SimpleOboImplementation and then create a PR when she's done as this is currently a blocker for PhEval.

**Comment by julesjacobsen** [comment]
@cmungall Can you suggest a good way to go about doing this? Would it be worth adding something to the API to return the current term for deprecated terms?

**Comment by cmungall** [comment]
Obo format isn't directly relevant here, it is what it is. You just need a way to query using metadata fields like replaced by and consider. This should be an easy addition

**Comment by cmungall** [comment]
You can do this right now by looping over all obsolete terms and looking up their metadata fields but a more direct method would be more ergonomic and efficient

**Comment by matentzn** [comment]
I didn't try but are you sure that alt_id annotations even get manifested as obsolete classes at all? Probably we should kill the alt_id: o pattern in our ontologies in favour of deprecate: o and replaced_by: a..

**Comment by cmungall** [comment]
@matentzn - in the OAK guide there is an explanation of "merged" aka alt IDs here: https://incatools.github.io/ontology-access-kit/guide/obsoletion.html#merged-entities

This hopefully clarifies

- they are not manifest as distinct obsolete class stanzas **at the obo format level**
- they are manifest as deprecated IRIs **at the RDF/OWL level**

However, there are some cases in HPO where an entity was deleted and a hasAlternateId has been manually added - these are currently not seen by OAK. We could add a special case for these, but these are technically wrong.
