### ISSUE TITLE
Cannot ingest MAXO

### ISSUE THREAD

**Issue by pnrobinson** [INCATools/ontology-access-kit#344]
Using this command
```
from oaklib.resource import OntologyResource
from oaklib.implementations.pronto.pronto_implementation import ProntoImplementation
resource = OntologyResource(slug='maxo.obo', local=True)
oi = ProntoImplementation(resource)
```

I get this
```
/home/peter/.local/lib/python3.10/site-packages/oaklib/implementations/pronto/pronto_implementation.py:143: UnicodeWarning: unsound encoding, assuming utf-8 (99% confidence)
  ontology = Ontology(str(resource.local_path), **kwargs)
Traceback (most recent call last):
  File "/home/peter/Downloads/MAXO/maxo-gene-review/parse_maxo.py", line 27, in <module>
    oi = ProntoImplementation(resource)
  File "<string>", line 11, in __init__
  File "/home/peter/.local/lib/python3.10/site-packages/oaklib/implementations/pronto/pronto_implementation.py", line 143, in __post_init__
    ontology = Ontology(str(resource.local_path), **kwargs)
  File "/home/peter/.local/lib/python3.10/site-packages/pronto/ontology.py", line 283, in __init__
    cls(self).parse_from(_handle)  # type: ignore
  File "/home/peter/.local/lib/python3.10/site-packages/pronto/parsers/obo.py", line 45, in parse_from
    raise SyntaxError(s.args[0], location) from None
  File "maxo.obo", line 35918
    xref: DPNL 2003:13063␊
               ^
SyntaxError: expected EOL or QuotedString
```

This may be an error with the creation of the MAXO OBO file (the xref is not a CURIE), but it would be nice to have the option for continuing the ingest despite the error
```
[Term]
id: FOODON:03411226
name: sesame plant
synonym: "Sesamum indicum L." NARROW []
synonym: "Sesamum orientale L." NARROW []
synonym: "simsim" EXACT []
xref: DPNL 2003:13063
xref: GRIN:33749
xref: http://eol.org/pages/4428
xref: http://www.langual.org/langual_thesaurus.asp?termid=B1226
xref: ITIS:505186
xref: MANSFELD:10138
xref: PLANTS:SEOR4
is_a: FOODON:03411017 ! oil-producing plant
is_a: FOODON:03411174 ! edible seed producing plant
property_value: hasSynonym "sesamum indicum" xsd:string
property_value: hasSynonym "sesamum orientale" xsd:string
```

**Comment by matentzn** [comment]
This is an important related issue: https://github.com/althonos/pronto/issues/159

**Comment by cmungall** [comment]
I filed an issue with foodon too. Yes ideally upstreams would not have this error, and ideally pronto would be more forgiving.

In the interim, there are a number of other options

## For the latest release version of MAXO

You can use the pre-built sqlite version. Just specify `sqlite:obo:maxo`

```python
>>> from oaklib.selector import get_implementation_from_shorthand
>>> oi = get_implementation_from_shorthand("sqlite:obo:maxo")
```

the first time you run this there will be a lag, after that the cached version will be used.

## For the edit version of MAXO

There are a number of options

1. Build the sqlite file yourself
2. use a different adapter, such as the rdf version working from the rdf file

I recommend 1, but currently this requires installing a few additional non-python components. This is a pain, but it will be simpler soon.

See: https://incatools.github.io/ontology-access-kit/intro/tutorial07.html

**Comment by pnrobinson** [comment]
thanks! Very cool tool!
The function I was looking for was this -- enter a term id and get all of the descendants. This does not seem to be easily possible with robot or oak (if it is, the documentation is tool complicated). I would up doing this with Protege which makes it trivial (although the output format is not great).
I think this issues is closable, let me know if I should do the closing?

**Comment by cmungall** [comment]
Does this do what you need:

```python
>>> from oaklib.selector import get_implementation_from_shorthand
>>> from oaklib.datamodels.vocabulary import IS_A
>>> oi = get_implementation_from_shorthand("sqlite:obo:maxo")
>>> for x in oi.ancestors("MAXO:0010066", predicates=[IS_A]):
...   print(x)
...
MAXO:0000001
MAXO:0000002
MAXO:0000009
MAXO:0000056
MAXO:0010066
```

I'll close for now but feel free to keep asking Qs on this issue or elsewhere!
