### ISSUE TITLE
Pass exclusion list to lexmatch and annotate

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-access-kit#349]
E.g. brand names for pesticides in chebi often result in false positive matches

**Comment by cmungall** [comment]
[BRANDS.txt](https://github.com/INCATools/ontology-access-kit/files/9993029/BRANDS.txt)

`grep BRAND ~/tmp/chebi.obo  | perl -npe 's@.*"(.*)".*@$1@' | sort -u`

**Comment by matentzn** [comment]
Can you explain this a bit more? Is the exclusion list like a list of "stop words" in the NLP sense, or will it simply not attempt to match any strings that contain any strings in the list? And why are brand names resulting in false positive matches?

**Comment by cmungall** [comment]
This would be entire strings

The use case we have in mind is pesticide brand names in chebi which causes
false positives in NER

**Comment by hrshdhgd** [comment]
Fixed by #353
