### ISSUE TITLE
`meta` as a param for `lexmatch`

### ISSUE THREAD

**Issue by hrshdhgd** [INCATools/ontology-access-kit#350]
When we `lexmatch` through the [CLI](https://github.com/INCATools/ontology-access-kit/blob/18e5ddd6f591d0d01f0cccd2ba6c2173b86dd183/src/oaklib/cli.py#L3433), it calls the [`lexical_index_to_sssom`](https://github.com/INCATools/ontology-access-kit/blob/18e5ddd6f591d0d01f0cccd2ba6c2173b86dd183/src/oaklib/cli.py#L3492) which in turn uses [`meta`](https://github.com/INCATools/ontology-access-kit/blob/18e5ddd6f591d0d01f0cccd2ba6c2173b86dd183/src/oaklib/utilities/lexical/lexical_indexer.py#L205) as a parameter. In the absence of the `meta` param, it uses a [default one from sssom](https://github.com/INCATools/ontology-access-kit/blob/18e5ddd6f591d0d01f0cccd2ba6c2173b86dd183/src/oaklib/utilities/lexical/lexical_indexer.py#L238).

Would it make sense for lexmatch to have the metadata parameter as well?

**Comment by cmungall** [comment]
prefix maps are passed at the command level, not the subcommand level, see

https://incatools.github.io/ontology-access-kit/cli.html#runoak

--named-prefix-map <named_prefix_map>[](https://incatools.github.io/ontology-access-kit/cli.html#cmdoption-runoak-named-prefix-map)
the name of a prefix map, e.g. obo, prefixcc

Currently you can

- pass individual prefix=namespace expansions
- pass in a named prefix map from prefixmaps

It would be useful to extend this to allow reading expansions from a file (csv or yaml)

this could easily be passed through to the sssom writer. I guess an issue with passing all through is that there are a large number that are never used.
