### ISSUE TITLE
Statistics option is not working as expected

### ISSUE THREAD

**Issue by souzadevinicius** [INCATools/ontology-access-kit#354]
The statistics option is not generating columns visits and distance.

**Steps to Reproduce:**
```
runoak --input prontolib:fbbt.obo ancestors FBbt:00004751 --predicates i,p --statistics
```
**Actual Result**

| id|label|
|---------------|------------------------------------------|
|FBbt:00004751  |wing vein                                 |
|rdfs:subClassOf|subClassOf                                |
|FBbt:00007245  |cuticular specialization                  |
|BFO:0000050    |part_of                                   |
|FBbt:00006015  |wing blade                                |
|FBbt:00007010  |multi-tissue structure                    |
|FBbt:00004729  |wing                                      |
|FBbt:00007000  |appendage                                 |
|FBbt:00003021  |adult mesothoracic segment                |
|FBbt:00004551  |adult external thorax                     |
|FBbt:00007289  |tagmatic subdivision of integument        |
|FBbt:00005396  |adult integumentary system                |
|FBbt:00003018  |adult thorax                              |
|FBbt:00000015  |thorax                                    |
|FBbt:00003005  |adult tagma                               |
|FBbt:00000002  |tagma                                     |
|FBbt:00003004  |adult                                     |
|FBbt:00000001  |organism                                  |
|FBbt:00100313  |multicellular structure                   |
|FBbt:00007001  |anatomical structure                      |
|FBbt:00007016  |material anatomical entity                |
|FBbt:10000000  |anatomical entity                         |
|FBbt:00057001  |anterior-posterior subdivision of organism|
|FBbt:00007009  |organism subdivision                      |
|FBbt:00004969  |integumentary system                      |
|FBbt:00004856  |organ system                              |
|FBbt:00007284  |region of integument                      |
|FBbt:00007330  |organ system subdivision                  |
|FBbt:00000018  |mesothoracic segment                      |
|FBbt:00003019  |adult thoracic segment                    |
|FBbt:00000016  |thoracic segment                          |
|FBbt:00003006  |adult segment                             |
|FBbt:00000003  |segment                                   |
|FBbt:00007013  |acellular anatomical structure            |
|FBbt:00004970  |cuticle                                   |

**Expected Result**
![image](https://user-images.githubusercontent.com/6750638/202225054-c375aec3-8702-4790-9912-49cb819b0ef6.png)

**Version**
oaklib                        **0.1.53**

**Comment by cmungall** [comment]
ah, looks like the default writer for `ancestors` is the Info writer, which doesn't do anything with this

The quick fix is to add `--output-type csv`, or:

`runoak --input prontolib:fbbt.obo ancestors FBbt:00004751 --predicates i,p --statistics -O csv`

Of course, this is pretty unintuitive, a closing action for this issue could be:

- emit an explicit error "info writer not compatible with --statistics"
- auto-switch to csv writer is statistics passed (I lean towards disliking this level of magic)
- add visits plus distance to the info writer.

**Comment by cmungall** [comment]
With the next release, the default output for ancestors will be csv

```
runoak --input prontolib:fbbt.obo ancestors FBbt:00004751 --predicates i,p  --statistics
```

will produce the table output

trying to force info writer with statistics will throw an error:

```
runoak --input prontolib:fbbt.obo ancestors FBbt:00004751 --predicates i,p  --statistics -O info
ValueError: StreamingInfoWriter (`-O info`) does not support --statistics output
```

note in the next release, stack traces are suppressed by default, unless `--stacktrace` is passed
