### ISSUE TITLE
--annotate-text does not work with bioportal for all but first line

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-access-kit#376]
```python
def annotate_file(
        self,
        text_file: TextIOWrapper,
        configuration: TextAnnotationConfiguration = None,
    ) -> Iterator[TextAnnotation]:
...
...
      return self.annotate_text(line, configuration)
```

there is no way for this to run over subsequent lines

See: https://realpython.com/lessons/looping-over-iterables/

Also:

 - annotate text throws error if `--annotate-text` is used and file has an empty line
 - there are various other typing issues

**Comment by hrshdhgd** [comment]
Can you give me an example you're facing this issue with?
