### ISSUE TITLE
`diff-via-mappings` docs may need to be updated

### ISSUE THREAD

**Issue by hrshdhgd** [INCATools/ontology-access-kit#388]
The [example for the command](https://incatools.github.io/ontology-access-kit/cli.html?highlight=diff%20via%20mappings#runoak-diff-via-mappings) `diff-via-mappings` does not have the command in it. Is it on purpose and I'm missing something or is it a typo that need fixing?

**Comment by cmungall** [comment]
it's an accidental omission
