### ISSUE TITLE
gilda makes bananas

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-access-kit#423]
```
✗ runoak -i gilda: annotate -W "Atypical Antipsychotic Agents"
object_id: CHEBI:CHEBI:65191
object_label: second generation antipsychotic
subject_end: 29
subject_start: 1
```

not sure if this is gilda itself or the way we wrap it - either way, OAK is a no-banana zone!

**Comment by hrshdhgd** [comment]
From the Gilda implementation:
```
curie=f"{match.term.db}:{match.term.id}",
```
`match.term.db` is the prefix (`CHEBI` in this case)
`match.term.id` is a CURIE itself (`CHEBI:65191` in this case)

Not sure what changed but it seems like dropping the `match.term.db` fixes the issue.

**Comment by cmungall** [comment]
note the bananas are not consistent

```
runoak -i gilda: annotate -W "SNCA"
object_id: HGNC:11138
object_label: SNCA
subject_end: 4
subject_start: 1
```

therefore the PR should *conservatively* remove bananas

**Comment by joeflack4** [comment]
I feel like I'm starting to see a proliferation of banana related content.
