### ISSUE TITLE
Add wrapper for `rustsim`

### ISSUE THREAD

**Issue by caufieldjh** [INCATools/ontology-access-kit#450]
We've begun to implement semantic similarity measures in Rust here: https://github.com/Knowledge-Graph-Hub/rustsim
It only includes Jaccard termset similarity at the moment but other methods are on the way.
The goal is to provide more performant methods with minimal additional dependencies.

It's on Pypi so OAK can import it and run it through a wrapper, though we'll need to take some care in dependency installation.
Most other OAK operations won't need Rust.

**Comment by cmungall** [comment]
See also

- #247

**Comment by caufieldjh** [comment]
This is present, rustsim is now semsimian; see https://github.com/INCATools/ontology-access-kit/pull/567
