### ISSUE TITLE
runoak mappings does not add valid curie_map

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-access-kit#462]
```
runoak -i sqlite:obo:uberon mappings -O sssom > tmp/anatomy-mapping-uberon.tsv
```

Results in a lot of mappings, but no `curie_map`.

**Comment by cmungall** [comment]
spoke to @hrshdhgd about how to do this, StreamingSssomWriter can do a `self.ontology_interface.prefix_map` to get the map

byt remember many ontologies are not well-behaved and do not contain prefix expansions for all xrefs. But here the user can choose to pass this in as a global option

e.g.

`runoak --named-prefix-map bioregistry -i sqlite:obo:uberon mappings -O sssom > tmp/anatomy-mapping-uberon.tsv`

however we still don't expect this to work for many prefixes

```
✗ runoak --named-prefix-map bioregistry prefixes FMA MBA BIRNLEX SCTID Wikipedia neuronames
key	val
FMA	http://purl.obolibrary.org/obo/FMA_
SCTID	http://snomed.info/id/
```

I think the default should still be to emit a mapping and have an optional strict mode

**Comment by hrshdhgd** [comment]
As of now `clean_prefix_map()` is strict and errors out if prefixes used in the dataframe do not have a corresponding `curie_map` . Should I add a flag `strict =True/False [default=False]` for  `clean_prefix_map()` in `sssom-py`?

**Comment by cmungall** [comment]
check with @matentzn but I think we need to allow this - we need to be able to extract messy unregistered xrefs from ontologies into sssom to analyze them in order to make progress on registering them. alternatively you can just inject into some kind of global unknown namespace

**Comment by matentzn** [comment]
The general thought "allow messy prefixes to be parsed" I guess is practical, but I am not sure this is a SSSOM problem - shouldn't the parser that registers the prefix guess, or randomly generates, a prefix map entry?

You could:
1. Take the prefixes from `self.ontology_interface.prefix_map` where they exist
2. Where they don't, check the sssom default context, or bioregistry directly
3. Where neither works, just generate a randomised prefix entry `BIRNLEX: http://w3id.org/oak/unknown_prefixes/birnlex`

The ontology parsing process basically builds up a prefix map which can then be used to finalise the SSSOM data frame.

I do not think we should permit missing prefix declarations in the `curie_map` - that is too much wild west and will just result in underspecificed mapping files. I hope this makes sense, if not, lets clarify!

**Comment by hrshdhgd** [comment]
>You could:
>
>1. Take the prefixes from self.ontology_interface.prefix_map where they exist
>2. Where they don't, check the sssom default context, or bioregistry directly
>3. Where neither works, just generate a randomised prefix entry BIRNLEX: http://w3id.org/oak/unknown_prefixes/birnlex

Do we do this in `oaklib` or `sssom-py` ?

**Comment by matentzn** [comment]
I would say oak. We already do something like that in SSSOM but I think the burden should be on the parser to try to interpret the ontology

**Comment by cmungall** [comment]
On Wed, Mar 15, 2023 at 3:34 AM Nico Matentzoglu ***@***.***>
wrote:

> The general thought "allow messy prefixes to be parsed" I guess is
> practical, but I am not sure this is a SSSOM problem - shouldn't the parser
> that registers the prefix guess, or randomly generates, a prefix map entry?
>
> You could:
>
>    1. Take the prefixes from self.ontology_interface.prefix_map where
>    they exist
>
>
Oh of course we should always do this

>
>    1.
>    2. Where they don't, check the sssom default context, or bioregistry
>    directly
>
>
I’d prefer this more explicitly under user control and to only use the
semantic subset in prefix maps. Generating an unstable prefix map with cgi
bin .pl expansions is worse than 3 below

>
>    1.
>    2. Where neither works, just generate a randomised prefix entry BIRNLEX:
>    http://w3id.org/oak/unknown_prefixes/birnlex
>
>
I like this

**Comment by matentzn** [comment]
Ok, so:

1. user supplied
2. self.ontology_interface.prefix_map
3. unknown prefix URI

Its not what we do in SSSOM toolkit for now, but I am fine with this option!

**Comment by matentzn** [comment]
You are right @hrshdhgd I didnt think this through.

What do you think about adding an else clause here:

https://github.com/mapping-commons/sssom-py/pull/353/files#diff-8e0eb781f6bf2cf74b9c6a904555d8bd7f214fef45ea8e55da8527f834e600e4R177

That takes the unknown prefixes and adds them to the mapping set, using `http://w3id.org/sssom/unknown_prefix/birnlex/`

as a value? Just thinking out loud here

**Comment by hrshdhgd** [comment]
The source for my confusion is where do we need to add this functionality: `oaklib` or `sssom-py`

**Comment by matentzn** [comment]
I think it should be `true` by default.
