### ISSUE TITLE
Documentation on how to run tests locally

### ISSUE THREAD

**Issue by manulera** [INCATools/ontology-access-kit#475]
Hello @cmungall, I think the docs to run the documentation to run the tests locally is not right:

```
poetry run python -m unittest
```

At least in my computer, this does not run certain tests because it fails to load oaklib as a dependency. Instead, I can run the tests locally if I activate the tox python environment:

```bash
# Activate poetry virtual env
poetry shell

# Install tox
pip install tox

# Something to create the tox virtual env (this must be ran at some point when running `poetry run tox` to run all checks)
???

# Activate the tox venv
. .tox/py/bin/activate

# Now you can run a test
python -m unittest tests/test_parsers/test_phaf_association_parser.py
```

Because all tests take so long, it's good to be able to run one before running the whole thing.

**Comment by cmungall** [comment]
hmm, which tests does it not run for you? I am able to run all tests locally and I don't think I have ever activated a tox environment. I only use tox for lint/flake8.

Anyone else get this? @hrshdhgd ?

**Comment by hrshdhgd** [comment]
Hi @manulera ! Just out of curiosity, did you run `poetry install` before all the above commands you mentioned?

**Comment by manulera** [comment]
Hi both. Sorry about that, I re-downloaded the project and did the same and now it worked. I had installed, but maybe did poetry shell in a different shell tab? In any case it works for me now. Sorry!
