### ISSUE TITLE
`mappings` command: Extract a valid license and mapping_set id 

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-access-kit#482]
Right now, this is extracted:

```
# license: UNSPECIFIED
# mapping_set_id: temp
```

These are both not valid according to the sssom data model.

I would suggest:

1. If the ontology as a dcterms:license property, propagate it through. If not use the sssom default license property (`https://w3id.org/sssom/license/unspecified`, but use from sssom package)
2. For mapping set id, just use the sssom-py default.

**Comment by hrshdhgd** [comment]
The `UNSPECIFIED` comes from [this line](https://github.com/INCATools/ontology-access-kit/blob/ae9b733bbf439932d04cbd47f52d6893a14d7db3/src/oaklib/utilities/mapping/sssom_utils.py#L75) that is called during the `mappings` CLI. What should it be changed to in `oaklib`?

cc: @cmungall

**Comment by cmungall** [comment]
Use `https://w3id.org/sssom/license/unspecified`
