### ISSUE TITLE
Unpin `poetry==1.4.0` in main.yml workflow.

### ISSUE THREAD

**Issue by hrshdhgd** [INCATools/ontology-access-kit#486]
The pinning was done because of GH action failures for Windows specifically. #469. I created a blank PR #485 to test this. Once Microsoft/GitHub fixes this issue, we can remove this pinning.

**Comment by dalito** [comment]
Hey @hrshdhgd, the poetry team [released 1.4.2](https://github.com/python-poetry/poetry/releases/tag/1.4.2) with a fix. Now it only prints a warning.

**Comment by hrshdhgd** [comment]
Thanks for letting know @dalito ! P.R started to close this issue: https://github.com/INCATools/ontology-access-kit/pull/516
