### ISSUE TITLE
Drawing the Relation Ontologies

### ISSUE THREAD

**Issue by raven44099** [INCATools/ontology-access-kit#524]
Hi, I am highly interested in working with the Ubergraph Relation Ontology.

Previously, I was able to retrieve the relationships and visualize the relationship ontology using this code, which doesn't work anymore (google colab) (see [issue ](https://github.com/INCATools/ubergraph/issues/120)):
```py
!pip install oaklib
from oaklib.implementations import UbergraphImplementation
from oaklib.utilities.obograph_utils import graph_to_image, default_stylemap_path
stylemap        = default_stylemap_path()
from IPython.display import Image

oi  =  UbergraphImplementation()
ubergraph_predicates = oi.relationships(predicates=['rdfs:subPropertyOf']) #is generator object
ubergraph_graph = oi.relationships_to_graph(ubergraph_predicates)
graph_to_image(ubergraph_graph, stylemap=stylemap, imgfile='xx.png')
Image('xx.png')
```
In particular, `oi.relationships(predicates=['rdfs:subPropertyOf'])` stopped working and even with `!pip install oaklib version==0.1.0` cannot make it work again. 

Furthermore, it also doesn't work for the `fbbt.obo` file:
```py
!wget http://purl.obolibrary.org/obo/fbbt.obo
from oaklib import get_adapter
oi = get_adapter("fbbt.obo")
```

# relation ontology graph

Even when the code was working, I had _three_ problems:
1. The resolution was too low to read the labels
2. Because there was no label, I had to look the color meanings up manually in the yaml file.
3. I wanted to remove the depricated relation types and apply other filters.

Thank you, and I appreciate your help!

**Comment by cmungall** [comment]
Sorry this isn't working for you!

I answered over on the ubergraph ticket but in the interim this should work:

```python
>>> from oaklib import get_adapter
>>> oi  =  get_adapter("sqlite:obo:ro")
```

**Comment by raven44099** [comment]
> ```python
> from oaklib import get_adapter
> >>> oi  =  get_adapter("sqlite:obo:ro")
> ```
Thank you, this works indeed for the RO relations.
