### ISSUE TITLE
CLI docs are missing

### ISSUE THREAD

**Issue by caufieldjh** [INCATools/ontology-access-kit#544]
The docs in https://incatools.github.io/ontology-access-kit/ appear to be missing descriptions of CLI commands, though they were visible quite recently.

**Comment by cmungall** [comment]
this is odd, when I build with sphinx locally I see them.

it's like sphinx is ignoring:

```
.. currentmodule:: oaklib.cli

.. click:: oaklib.cli:main
    :prog: runoak
    :show-nested:
```

**Comment by cmungall** [comment]
ah, looks like this was caused by a manual deploy to gh-pages. possibly using a different setup. To fix we'll need to make a change to cli.rst in order to trigger a rebuild...

**Comment by cmungall** [comment]
forcing changes to cli.rst didn't seem to help:

https://github.com/INCATools/ontology-access-kit/commit/489cbb5c0a36f85aeac1260d70c9be88aa5382a8#diff-3d5d56e1aff4662b263b3f412d07a14b93b118f7a1c0f6934efd1f116323e046

**Comment by cmungall** [comment]
still can't figure out how to get them back

**Comment by cmungall** [comment]
and they are now back. I am not sure how but we could look at the changes in poetry.lock to determine if this happens again
