### ISSUE TITLE
extract-triples sometimes leaves owl axioms incomplete leading to ErrorNs in owlapi

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-access-kit#55]
To replicate:

```bash
runoak -i ubergraph:uberon extract-triples UBERON:0001463 -o finger1.ttl -O ttl
```

the ttl looks OK at first, but if we visualize:

```bash
runoak -i finger1.ttl viz UBERON:0001463 -p i,p 
```

we get truncated graphs

<img width="578" alt="image" src="https://user-images.githubusercontent.com/50745/166300072-630523b1-b6fd-4b2d-a2bd-5563c2b02cf7.png">

in protege: 
<img width="260" alt="image" src="https://user-images.githubusercontent.com/50745/166300182-df3cdeca-fea9-46e4-9dd5-6cc92decd333.png">

under manus we have:

```turtle
    rdfs:subClassOf [ a owl:Restriction ;
            owl:onProperty ns1:RO_0002551 ;
            owl:someValuesFrom ns1:UBERON_0001442 ],
        [ a owl:Restriction ;
            owl:onProperty ns1:RO_0002202 ;
            owl:someValuesFrom ns1:UBERON_0006875 ] ;
    owl:equivalentClass [ ] ;
```

for some reason the subclass axiom isn't extracted, and the equivalence axiom is to a blank node

**Comment by matentzn** [comment]
RO_0002551 could be missing OP declaration, perhaps even UBERON_0001442?

**Comment by cmungall** [comment]
aha! I have found the cause of the graph truncation

the is-a relationship from manus is not in uberon-base:

https://api.triplydb.com/s/h4cG-dj2E

This is not unexpected for a base file - subClassOf axiom only appears after reasoning

I think a general recommendation for ubergraph should be to not restrict by ontology, always query the whole graph

this resolves the main mystery. We still need to fix it such that we don't truncate at the owl axiom level

**Comment by cmungall** [comment]
OK, the fix is to always include base + RelationGraphEnum.ontology
