### ISSUE TITLE
Apply taxon constrain to GO enrichment

### ISSUE THREAD

**Issue by manulera** [INCATools/ontology-access-kit#556]
Hello,

I have the following runoak command for a PomBase GO enrichment:

```bash
runoak -i sqlite:obo:go \
    -G gaf -g data/gene_association.gaf \
    enrichment -p i,p \
    -U lists/example.tsv \
    -B background_lists/protein_coding.txt \
    -O csv -o results/example_GO_enrichment.tsv \
    --cutoff 0.05
```

How should I apply a taxon constrain for the enrichment? Thanks!

**Comment by cmungall** [comment]
You can pass in your own hypotheses as a set of GO IDs using the standard OAK methods (list of IDs on the command line, or `.idfile <FILE.txt>`'

However, this won't buy you anything. Any term with <2 annotations will be excluded from hypotheses anyway. So unless your background is something exotic and multi-species, only pombe terms will be considered.

Now, there is potentially moderate value in excluding grouping classes that only make sense in a multi-species context. But tbh there are few of these and no systematic way to get them, and mostly on metazoa relevant (e.g. "'generic' eye development)

**Comment by manulera** [comment]
Thanks @cmungall, that's very helpful!
