### ISSUE TITLE
Rethink sssom strict mode as default for lexmatch

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-access-kit#587]
I frequently run lexmatch on a new set, wait, then see a message

ValueError: ['<IDSPACE>'] are used in the SSSOM mapping set but it does not exist in the prefix map

I then remember to set `--no-ensure-strict-prefixes`

Either:

- `--no-ensure-strict-prefixes` should be default
- an automatic repair with warnings should be default
- an initial scan should be performed and failure should happen *before* my CPU has wasted a lot of cycles doing an alignment

**Comment by matentzn** [comment]
Can we generate a random prefix and curify in this case, adding logger warning?

**Comment by cmungall** [comment]
you mean a random prefix expansion? I think having some kind of example.org/unknown/ type default expansion + warning would be ok. This would be trivial to fix in the header during post-processing / editing

**Comment by hrshdhgd** [comment]
I remember fixing the code such that `""` is not flagged as a missing prefix. Which version of `sssom-py` is this?

**Comment by cmungall** [comment]
https://github.com/INCATools/ontology-access-kit/blob/e98824ea0093ce0bfae31c95afbd7ba47dd82259/pyproject.toml#L17

**Comment by hrshdhgd** [comment]
Yeah  then this should not be happening. Can you show me an example for this?
