### ISSUE TITLE
`relationships`: (i) subClassOf only default, (ii) `--predicates` failure?

### ISSUE THREAD

**Issue by joeflack4** [INCATools/ontology-access-kit#613]
## Overview
I'm trying to get a list of relationships for a term, but I find that (i) when I don't list any `--predicates`, it only shows me `subClassOf` relationships, and (ii) when I do list explicit `--predicates`, I get nothing back in response.

See here where I'm creating the ontology file and running this command: https://github.com/monarch-initiative/mondo/pull/6451#discussion_r1264775511

```owl
    <owl:Class rdf:about="http://purl.obolibrary.org/obo/MONDO_0000004">
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/MONDO_0002816"/>
        <rdfs:subClassOf>
            <owl:Restriction>
                <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/RO_0004024"/>
                <owl:someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/GO_0034651"/>
            </owl:Restriction>
        </rdfs:subClassOf>
        <rdfs:subClassOf>
            <owl:Restriction>
                <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/RO_0004026"/>
                <owl:someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/UBERON_0001235"/>
            </owl:Restriction>
        </rdfs:subClassOf>
        <obo:IAO_0000115>An endocrine or hormonal disorder that occurs when the adrenal cortex does not produce enough of the hormone cortisol and in some cases, the hormone aldosterone. It may be due to a disorder of the adrenal cortex (Addison&apos;s disease or primary adrenal insufficiency) or to inadequate secretion of ACTH by the pituitary gland (secondary adrenal insufficiency).</obo:IAO_0000115>
        <oboInOwl:hasDbXref>DOID:10493</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref>GARD:0006722</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref>ICD9:255.4</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref>ICD9:255.41</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref>MESH:D000309</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref>NCIT:C26691</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref>SCTID:154707007</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref>SCTID:190527008</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref>SCTID:267398003</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref>SCTID:267483004</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref>SCTID:386584007</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref>SCTID:68588005</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref>UMLS:C0001623</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref>UMLS:C0405580</oboInOwl:hasDbXref>
        <oboInOwl:hasExactSynonym>adrenal cortical hypofunction</oboInOwl:hasExactSynonym>
        <oboInOwl:hasExactSynonym>adrenal cortical insufficiency</oboInOwl:hasExactSynonym>
        <oboInOwl:hasExactSynonym>adrenal gland insufficiency</oboInOwl:hasExactSynonym>
        <oboInOwl:hasExactSynonym>adrenal insufficiency</oboInOwl:hasExactSynonym>
        <oboInOwl:hasExactSynonym>adrenocortical insufficiency</oboInOwl:hasExactSynonym>
        <oboInOwl:hasExactSynonym>corticoadrenal insufficiency</oboInOwl:hasExactSynonym>
        <oboInOwl:hasExactSynonym>hypocortisolemia</oboInOwl:hasExactSynonym>
        <oboInOwl:hasExactSynonym>hypocortisolism</oboInOwl:hasExactSynonym>
        <oboInOwl:hasRelatedSynonym>hypoadrenalism</oboInOwl:hasRelatedSynonym>
        <oboInOwl:id>MONDO:0000004</oboInOwl:id>
        <rdfs:label>adrenocortical insufficiency</rdfs:label>
    </owl:Class>
```

(i) `subClassOf` only default
`runoak -i sqlite:tmp/mondo-edit.db relationships -p i MONDO:0000004`

Result:
```tsv
subject	subject_label	predicate	predicate_label	object	object_label
MONDO:0000004	adrenocortical insufficiency	rdfs:subClassOf	None	MONDO:0002816	adrenal cortex disorder
```

(ii) `--predicates` failure?
`runoak -i sqlite:tmp/mondo-edit.db relationships -p i MONDO:0000004 --predicates oboInOwl:hasDbXref skos:exactMatch skos:narrowMatch skos:broadMatch skos:relatedMatch`

Result: None

**Comment by cmungall** [comment]
OAK distinguishes between [Relationships](https://incatools.github.io/ontology-access-kit/glossary.html#term-Relationship) and [Mapping](https://incatools.github.io/ontology-access-kit/glossary.html#term-Mapping).

See also the more detailed elucidation in the [OAK guide](https://incatools.github.io/ontology-access-kit/guide)

 - https://incatools.github.io/ontology-access-kit/guide/relationships-and-graphs.html
 - https://incatools.github.io/ontology-access-kit/guide/mappings.html

The command is behaving as expected, as dbXref isn't a relationship.

You can query for mappings with the `mappings` command. This follows the SSSOM data model

```
$ mondo mappings MONDO:0000004 -O sssom
# curie_map:
#   <http: http://w3id.org/sssom/unknown_prefix/<http/
#   DOID: http://purl.obolibrary.org/obo/DOID_
#   GARD: http://purl.obolibrary.org/obo/GARD_
#   ICD9: http://w3id.org/sssom/unknown_prefix/icd9/
#   MESH: http://id.nlm.nih.gov/mesh/
#   MONDO: http://purl.obolibrary.org/obo/MONDO_
#   NCIT: http://purl.obolibrary.org/obo/NCIT_
#   SCTID: http://www.snomedbrowser.com/Codes/Details/
#   UMLS: http://linkedlifedata.com/resource/umls/id/
#   oio: http://www.geneontology.org/formats/oboInOwl#
#   owl: http://www.w3.org/2002/07/owl#
#   rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
#   rdfs: http://www.w3.org/2000/01/rdf-schema#
#   semapv: https://w3id.org/semapv/
#   skos: http://www.w3.org/2004/02/skos/core#
#   sssom: https://w3id.org/sssom/
# license: https://w3id.org/sssom/license/unspecified
# mapping_set_id: temp
subject_id	subject_label	predicate_id	object_id	mapping_justification	subject_source	object_source
MONDO:0000004	adrenocortical insufficiency	oio:hasDbXref	DOID:10493	semapv:UnspecifiedMatching	MONDO	DOID
MONDO:0000004	adrenocortical insufficiency	oio:hasDbXref	GARD:0006722	semapv:UnspecifiedMatching	MONDO	GARD
MONDO:0000004	adrenocortical insufficiency	oio:hasDbXref	ICD9:255.4	semapv:UnspecifiedMatching	MONDO	ICD9
MONDO:0000004	adrenocortical insufficiency	oio:hasDbXref	ICD9:255.41	semapv:UnspecifiedMatching	MONDO	ICD9
MONDO:0000004	adrenocortical insufficiency	oio:hasDbXref	MESH:D000309	semapv:UnspecifiedMatching	MONDO	MESH
MONDO:0000004	adrenocortical insufficiency	oio:hasDbXref	NCIT:C26691	semapv:UnspecifiedMatching	MONDO	NCIT
MONDO:0000004	adrenocortical insufficiency	oio:hasDbXref	SCTID:386584007	semapv:UnspecifiedMatching	MONDO	SCTID
MONDO:0000004	adrenocortical insufficiency	oio:hasDbXref	UMLS:C0405580	semapv:UnspecifiedMatching	MONDO	UMLS
MONDO:0000004	adrenocortical insufficiency	skos:exactMatch	<http://identifiers.org/mesh/D000309>	semapv:UnspecifiedMatching	MONDO	<http
MONDO:0000004	adrenocortical insufficiency	skos:exactMatch	<http://identifiers.org/snomedct/386584007>	semapv:UnspecifiedMatching	MONDO	<http
MONDO:0000004	adrenocortical insufficiency	skos:exactMatch	<http://linkedlifedata.com/resource/umls/id/C0405580>	semapv:UnspecifiedMatching	MONDO	<http
MONDO:0000004	adrenocortical insufficiency	skos:exactMatch	DOID:10493	semapv:UnspecifiedMatching	MONDO	DOID
MONDO:0000004	adrenocortical insufficiency	skos:exactMatch	NCIT:C26691	semapv:UnspecifiedMatching	MONDO	NCIT
```

(comments on the apparent duplication here #611)

Currently the mappings command doesn't allow you to filter by mapping predicate, open an issue if you want this, it should be easy to add.

**Comment by joeflack4** [comment]
Thanks @cmungall . Yesterday I tried out a bunch of different commands, and I also found that `mappings` is what I needed.

On a philosophical / design note, I can conceive of why one would not consider mapping predicates, or `oboInOwl:hasDbXref` to be a relationship. Just in case you haven't considered any of the following, I want to mention a few things.

1. A lot of people would consider mappings to be a subset of relationships. As one example, they're considered such in OMOP. There is a `relationship` table, with a `relationship_type` column, and all kinds of mapping predicates are there.
2. If my literal reading of [_relationship_ in the OAK glossary](https://incatools.github.io/ontology-access-kit/glossary.html#term-Relationship) is correct, it would seem that these mapping predicates should be included:
> A [Relationship](https://incatools.github.io/ontology-access-kit/glossary.html#term-Relationship) is a type connection between two ontology elements. The first element is called the Subject, and the second one the Object, with the type of connection being the [Predicate](https://incatools.github.io/ontology-access-kit/glossary.html#term-Predicate). Sometimes Relationships are equated with [Triples](https://incatools.github.io/ontology-access-kit/glossary.html#term-Triple) in [RDF](https://incatools.github.io/ontology-access-kit/glossary.html#term-RDF) but this can be confusing, because some relationships map to multiple triples when following the OWL RDF serialization. An example is the relationship “finger part-of hand”, which in OWL is represented using a Existential Restriction that maps to 4 triples.

**Comment by joeflack4** [comment]
Another potential request. Would it not be too difficult to raise an error if the `--predicates` a user passes includes something unexpected? It sounds like `relationships` knows precisely what subset of predicates it expects. Could we not check against that same subset to raise an error?

If the subset is not too large, it could be included in the docs as well.

**Comment by cmungall** [comment]
Great idea!

**Comment by joeflack4** [comment]
Thanks @cmungall. I also wanted you to check out this other comment as well: https://github.com/INCATools/ontology-access-kit/issues/613#issuecomment-1638914583 , particularly how OMOP considers relationships, etc
