### ISSUE TITLE
Submit oak lexmatch (or generate-mappings) to OAEI 2023

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-access-kit#617]
There is not really a goal here to win - the idea is to just get it in and see how it fares, and maybe use this opportunity also to up our own game of improving our alignment tools. Another goal is to ensure that at least one system in OAEI 2023 has a valid SSSOM output!

Here are the instructions:

http://oaei.ontologymatching.org/2023/melt/index.html

Lets go down the docker route (MatcherDockerFile). We should aim for July 31st for an initial submission.

**Comment by cmungall** [comment]
too late, but feel free to reopen for 2024
