### ISSUE TITLE
Add ability to pass a limited closure table to semsimian

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-access-kit#619]
phenio.db:

```
sqlite> select count(*) from entailed_edge where predicate ='rdfs:subClassOf';
5675458
sqlite> select count(*) from entailed_edge;
46854391
```

it is useful to have the option to use any closure, but if the application knows in advance the union of all possible query predicates then we reduce the size of the python object that has to be passed to rust by ~10x

**Comment by cmungall** [comment]
@hrshdhgd I think this is done?

**Comment by hrshdhgd** [comment]
Yes!
