### ISSUE TITLE
outdated cell ontology

### ISSUE THREAD

**Issue by noamiz5060** [INCATools/ontology-access-kit#635]
Hello friends,
First of all, thank you for the tools you've developed, much appreciated

I'm using your package for looking at descendants and ancestors in my ontology
`from oaklib.resource import OntologyResource`
`from oaklib.datamodels.vocabulary import IS_A, PART_OF`
`from oaklib.implementations.sqldb.sql_implementation import SqlImplementation`

`cl_sql = SqlImplementation(OntologyResource(slug=f"sqlite:///cl.db", local=True))`
`cell_id_list_sql = list(cl_sql.descendants('CL:0000548', predicates=[IS_A, PART_OF]))`

I'm using it with cell ontology 
`onto_path = 'https://purl.obolibrary.org/obo/cl/cl-basic.obo'`
`graph = obonet.read_obo(onto_path)`

I've noticed that yours is outdated 
Some of the cells are deprecated and it hasn't been updated since
examples: CL:0000086, CL:0000398,  CL:0000085

https://www.ebi.ac.uk/ols4/ontologies/cl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCL_0000085
https://www.ebi.ac.uk/ols4/ontologies/cl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCL_0000398
https://www.ebi.ac.uk/ols4/ontologies/cl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCL_0000086

I really hope you could fix it 

Again, your work is much appreciated

**Comment by cmungall** [comment]
Thanks for the comments! I'm not sure I understand though. It seems you are downloading a copy of cl from somewhere that is out of date?

**Comment by noamiz5060** [comment]
> Thanks for the comments! I'm not sure I understand though. It seems you are downloading a copy of cl from somewhere that is out of date?

oh, I'm realizing you're right
I guess it makes my question irrelevant to this page. , 
Is it ok if I still ask a question about it though? It is fully understand if not
Is it possible apply the cell ontology from obolibrary (the one that is in the onto_path) into the OntologyResource? what should I write in the 'slug= ' ?

**Comment by cmungall** [comment]
@noamiz5060 I'm going to close this but feel free to open if you think something is wrong!
