### ISSUE TITLE
Add ability to easily retrieve axiom annotations (metadata) on relationships

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-access-kit#654]
The `relationships` method yields simple triples, either add a new method to retrieve these with axiom annotations (metadata) -- or add a general axiom_annotations method.

Note that many implementations are already able to do this, the ability is just not yet surfaced.

**Comment by joeflack4** [comment]
I like this suggestion. My preference would be to add a `include_axiom_annotations` or `include_metadata` param to `.relationships()` and default to `False`.

From there, I'm not 100% confident about this next recommendation, but you could have `.relationships()` call new method `.axiom_annotations()`/ `.relationship_metadata()`, which might support params like `subject_ids`, `object_ids`, and/or `relationships`.
