### ISSUE TITLE
New sssom==0.3.42 breaks oaklib

### ISSUE THREAD

**Issue by rly** [INCATools/ontology-access-kit#664]
`sssom==0.3.42` was released a few hours ago but breaks importing of oaklib. 

In a clean python 3.11 environment on Mac M1:
```
$ pip install oaklib
$ python -c "import oaklib"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/rly/mambaforge/envs/test/lib/python3.11/site-packages/oaklib/__init__.py", line 7, in <module>
    from oaklib.interfaces import BasicOntologyInterface  # noqa:F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rly/mambaforge/envs/test/lib/python3.11/site-packages/oaklib/interfaces/__init__.py", line 8, in <module>
    from oaklib.interfaces.text_annotator_interface import TextAnnotatorInterface
  File "/Users/rly/mambaforge/envs/test/lib/python3.11/site-packages/oaklib/interfaces/text_annotator_interface.py", line 22, in <module>
    from oaklib.utilities.lexical.lexical_indexer import create_or_load_lexical_index
  File "/Users/rly/mambaforge/envs/test/lib/python3.11/site-packages/oaklib/utilities/lexical/lexical_indexer.py", line 18, in <module>
    from sssom.context import get_default_metadata
ImportError: cannot import name 'get_default_metadata' from 'sssom.context' (/Users/rly/mambaforge/envs/test/lib/python3.11/site-packages/sssom/context.py)
```

In https://github.com/mapping-commons/sssom-py/pull/421 it looks like `get_default_metadata` was removed from `sssom/src/sssom/context.py` but this function is used in `oaklib/src/oaklib/utilities/lexical/lexical_indexer.py`

It looks like `oaklib` should use instead:
```python
from .typehints import Metadata
default_metadata = Metadata.default()
```

I think either `oaklib` should be updated with the above, or `sssom` should be updated to maintain the old `get_default_metadata` function while it is being deprecated.

**Comment by matentzn** [comment]
@rly thanks a ton.

This should not ever happen, I am not sure how I missed this but somehow the I must have allowed a PR in sssom-py through that removes a method (which I would not do usually if I had my full mental capacity).

@hrshdhgd can you re-introduce that method in SSSOM, formally `@deprecate` it and make a new release? Also, before you make a release, can you run all the OAK tests with the new sssom version so we can be sure that nothing else has broken?

**Comment by cthoyt** [comment]
@hrshdhgd I will take care of it

**Comment by cthoyt** [comment]
We yanked the 0.3.42 release, these breaking changes will get put into a 0.4.0 series and OAK will be updated to use the new code in #666

**Comment by rly** [comment]
Thanks for the update!
