### ISSUE TITLE
Can't run tests without LinkML

### ISSUE THREAD

**Issue by cthoyt** [INCATools/ontology-access-kit#665]
I installed oak with `pip install -e .[tests]` but it appears that linkml is a requirement for tests and is not installed. The solution is to add an optional dependency for `linkml` in the `tests` group, but I don't know how to do this with poetry.

**Comment by cmungall** [comment]
I'd recommend using poetry for running the test suite.

Currently the test dependencies (including linkml) are in dev-dependencies. I had assumed this was fairly standard for poetry, but the docs seem to suggest both: https://python-poetry.org/docs/master/managing-dependencies/
