### ISSUE TITLE
Bug?: `.relationships()` filtering predicates even if `predicates` arg absent

### ISSUE THREAD

**Issue by joeflack4** [INCATools/ontology-access-kit#675]
## Overview
In the docstring for these functions, e.g. in `BasicOntologyInterface`, it says: `:param predicates: constrain search to these predicates`. So I would expect that if this is not passed, we would get all relationships back regardless of predicates.

## Expected behavior
When you don't pass the `predicates` arg, I would expect to get all relationships regardless of predicate.

## Actual behavior
Some relationships do not get returned, based on what appears to be filtering of certain predicates.

## Example
Using `mondo.db` in [this PR](https://github.com/monarch-initiative/mondo-ingest/pull/363#discussion_r1328026714).
```py
# Using predicates arg
# - result: 3 preds: {'rdfs:subClassOf', 'skos:exactMatch', 'skos:narrowMatch'}
example1_rels = [x for x in oi.relationships(
    subjects=mondo_ids,
    predicates=['rdfs:subClassOf', 'oboInOwl:hasDbXref', 'skos:exactMatch', 'skos:broadMatch', 'skos:narrowMatch'])]
example1_preds = set([x[1] for x in example1_rels])

# Not using predicates arg
# - result: 6 preds: {'RO:0002573', 'RO:0004021', 'RO:0004024', 'obo:mondo#predisposes_towards', 'RO:0004029', 'rdfs:subClassOf'}
# however it's filtering out at the very least 2 predicates in the first example: 'skos:exactMatch', 'skos:narrowMatch'
example2_rels = [x for x in oi.relationships(subjects=mondo_ids)]
example2_preds = set([x[1] for x in example2_rels])
```

## Additional information
Context:
- [PR discussion](https://github.com/monarch-initiative/mondo-ingest/pull/363#discussion_r1328026714)
- [slack thread](https://obo-communitygroup.slack.com/archives/C03D93DEALA/p1695343465485099)

**Comment by joeflack4** [comment]
Is one issue that triples for some of these predicates are not considered "relationships"?

I don't have the screenshots / things to attach (I had more examples) because my previous computer died, but in the work I was doing for [omop2owl-vocab](https://github.com/HOT-Ecosystem/omop2owl-vocab), I noticed that my OWL had several `oboInOwl:hasDbXref` instances, but when I converted that to a SemanticSQL DB and looked at the `statements` table, none of those triples were there.

**Comment by cmungall** [comment]
Duplicate:

- #613

**Comment by joeflack4** [comment]
@cmungall Hmm, I guess this does have like 80% overlap with that issue. That wasn't long ago, so sorry that this didn't occur to me.

However, a few things I don't like that I would still consider issues:
1. **Throw warning**: If OAK, based on some convention, does not consider mapping edges "relationships" (_I understand the logic, but my intuition (and OMOP's) leans towards mappings being a subset of relationships_), then `.relationships()` should not return those mapping predicates even if I ask for them, or better yet should throw a warning or error.
 - Looks like this I suggested the same [in the other thread](https://github.com/INCATools/ontology-access-kit/issues/613#issuecomment-1639051106), so I'll open an issue
3. **New method?**: Is it possible to have some more general method, something like `.edges()` that returns both mapping and non-mapping relationships?

**Comment by joeflack4** [comment]
I don't know if it is discouraged but if I really wanted to I suppose I might use `.edge_index()` if I really wanted to return all edges (mappings and relationships) at once.
