### ISSUE TITLE
Missing support for Python 3.12

### ISSUE THREAD

**Issue by Silvanoc** [INCATools/ontology-access-kit#703]
[Claimed support for Python 3.12](https://pypi.org/project/oaklib/) is missing.

The installation fails due to dependencies that cannot be installed on Python 3.12:

* oaklib [depends on semsimian ^0.2.1](https://github.com/INCATools/ontology-access-kit/blob/15bf85cefc2fe8541b38aabfcf7c65eb46bc1231/pyproject.toml#L38)
* no build of semsimian exists for Python 3.12, currently [builds exist for 3.7 =< Python =< 3.11](https://github.com/monarch-initiative/semsimian/blob/0ae82eb20c169037344de1bcbb5523a1887c95f7/.github/workflows/release.yml).

This issue is [blocking support for Python 3.12 in `schema-automator`](https://github.com/linkml/schema-automator/issues/134).

**Comment by cmungall** [comment]
We should fix this but we can also make semsimian an optional dependency

**Comment by Silvanoc** [comment]
PR to replace support for 3.7 with support for 3.12 provided: https://github.com/monarch-initiative/semsimian/pull/121

**Comment by cmungall** [comment]
We should also add 3.12 to the test matrix

**Comment by hrshdhgd** [comment]
Adding it to the [next PR](https://github.com/INCATools/ontology-access-kit/pull/716)
