### ISSUE TITLE
Misleading copyright statement at the bottom of OAK documentation pages

### ISSUE THREAD

**Issue by nlharris** [INCATools/ontology-access-kit#710]
Chris just added a new documentation page, https://incatools.github.io/ontology-access-kit/howtos/use-llms
At the bottom it says
>  © Copyright 2022, OAK developers.

This is misleading because it implies the content of the page was created in 2022 (before LLMs were even a widely available thing!), plus "copyright" has a legal meaning that may or may not (I'm not a lawyer) differ from what the [LICENSE](https://github.com/INCATools/ontology-access-kit/blob/main/LICENSE) says.

The good news is that I found that Copyright text in https://github.com/INCATools/ontology-access-kit/blob/main/docs/conf.py, so I can just change it. I just wanted to check what I should change it to.

**Comment by cmungall** [comment]
Go for it!

**Comment by nlharris** [comment]
Ok! I just wanted to check what I should change it to. Should I just change 2022 to 2024 and leave the Copyright OAK developers as is?

**Comment by nlharris** [comment]
Maybe @kltm has thoughts on this

**Comment by kltm** [comment]
Once the copyright holder is figured out (ideally an entity that can be contacted for queries and can handle licensing questions), we can figure out how to fix the LICENSE in the repo, which lacks any information, like date and copyright holding entity. If "OAK developers" is what you're going with, it would be good to have contact information, or something.
There is no reason that I can see that the date should not be the last date of committed code by the "entity", which would be 2024. (IANAL, etc.)

**Comment by nlharris** [comment]
Ok, I'm unassigning myself because I don't know the answer to who the copyright holder should be.
