### ISSUE TITLE
Error during information-content execution

### ISSUE THREAD

**Issue by souzadevinicius** [INCATools/ontology-access-kit#725]
I'm trying to execute `--information-content` command with this arguments:

`runoak -vvv -g gene_phenotype.10090.tsv -i sqlite:obo:mp information-content -p i --use-associations i^MP: -o test.tsv`

TSV used for -g flag:
[gene_phenotype.10090.tsv.gz](https://github.com/INCATools/ontology-access-kit/files/14774371/gene_phenotype.10090.tsv.gz)

During its execution, this error is raised:

`ValueError: syntax must be specified`

The example in the documentation is:

`runoak -g hpoa.tsv -G hpoa -i hp.db information-content -p i –use-associations .all`

The documentation does not provide any description for the "-G" flag.

https://incatools.github.io/ontology-access-kit/cli.html#runoak-information-content

**Comment by hrshdhgd** [comment]
Additional info to replicate: 
```
ValueError: Mus musculus is not a valid URI or CURIE
```

whereas it is a label.

**Comment by hrshdhgd** [comment]
Dug deeper, I will need some direction here @cmungall .

The header of the tsv file is 

| subject | subject_label | subject_taxon | subject_taxon_label | negated | predicate | object | object_label | qualifierpublications | has_evidence | primary_knowledge_source | aggregator_knowledge_source |
|---------|---------------|---------------|---------------------|---------|-----------|--------|--------------|-----------------------|--------------|--------------------------|------------------------------|

Now from `hpoa_association_parser.py`

```
    subject_column: ColumnReference = field(default_factory=lambda: ColumnReference(0))
    subject_label_column: ColumnReference = field(default_factory=lambda: ColumnReference(1))
    predicate_column: ColumnReference = None
    object_column: ColumnReference = field(default_factory=lambda: ColumnReference(3))

```
`object_column` index points to `subject_taxon_label` column. Hence the error. 

There are many ways to resolve this. Before I go on and write up a solution, I want to check with you as to how you want to proceed.

**Comment by hrshdhgd** [comment]
THE PR fails, so clearly it is not a solution.

**Comment by cmungall** [comment]
Two separate formats, see https://hpo.jax.org/app/data/annotation-format 

- hpoa, aka phenotype.hpoa is for d2p
- hpoa_g2p aka genes_to_phenotype.txt is for g2p

This works:

```
runoak -i sqlite:obo:mp -g ~/Downloads/gene_phenotype.10090.tsv -G hpoa_g2p information-content -p i MP:0008770
id	information_content
MP:0008770	15.045802313751263
```

Sorry for the confusion! Yes, the association handling needs better docs! Coming soon!

**Comment by cmungall** [comment]
Some docs on associations here: https://incatools.github.io/ontology-access-kit/guide/associations.html

But this needs to enumerate the different association formats

Note you can bundle a config that combines ontologies, association files, and normalizers, see:

https://github.com/INCATools/ontology-access-kit/blob/main/notebooks/Monarch/Disease2GeneAnalysis.ipynb
