### ISSUE TITLE
Missing `defusedxml` dependency

### ISSUE THREAD

**Issue by gouttegd** [INCATools/ontology-access-kit#743]
A fresh install of `oaklib` version 0.6.4 (latest release) fails to run because of a missing `defusedxml` package:

```sh
$ python -m pip install oaklib
[…]
Successfully installed SPARQLWrapper-2.0.0 SQLAlchemy-2.0.29 […] wrapt-1.16.0 zipp-3.18.1

$ runoak
Traceback (most recent call last):
  File "/home/damien/t2/bin/runoak", line 5, in <module>
    from oaklib.cli import main
  File "/home/damien/t2/lib64/python3.9/site-packages/oaklib/__init__.py", line 8, in <module>
    from oaklib.interfaces import BasicOntologyInterface  # noqa:F401
  File "/home/damien/t2/lib64/python3.9/site-packages/oaklib/interfaces/__init__.py", line 9, in <module>
    from oaklib.interfaces.validator_interface import ValidatorInterface
  File "/home/damien/t2/lib64/python3.9/site-packages/oaklib/interfaces/validator_interface.py", line 22, in <module>
    from oaklib.utilities.publication_utils.pubmed_wrapper import PubmedWrapper
  File "/home/damien/t2/lib64/python3.9/site-packages/oaklib/utilities/publication_utils/pubmed_wrapper.py", line 11, in <module>
    from defusedxml.ElementTree import fromstring
ModuleNotFoundError: No module named 'defusedxml'
```

This seems to come from the newly introduced `pubmed_wrapper` module, which indeed imports `defusedxml` but the dependency does not seem to be declared anywhere.

**Comment by matentzn** [comment]
I noticed this as well; I thought it was a mistake in my environment..

**Comment by gouttegd** [comment]
I only noticed it when investigating why the “ontobot-change-agent” failed to process this issue in Uberon: https://github.com/obophenotype/uberon/issues/3265

The standard Python environment I routinely use on my machine does have `defusedxml` installed, so I missed it.

**Comment by cmungall** [comment]
Aha, this is why it doesn't show up in a test environment:

```
jupyter-server 2.14.0 The backend—i.e. core services, APIs, and REST endpoints—to Jupyter web applications.
└── nbconvert >=6.4.4
    ├── beautifulsoup4 *
    │   └── soupsieve >1.2
    ├── bleach !=5.0.0
    │   ├── six >=1.9.0
    │   └── webencodings *
    ├── defusedxml *
```

So it looks like this comes in via an extra 

This particular issue is easy to fix but we want to stop this happening again, we need to change our test strategy, such that we run all tests that don't depend on extras in the equivalent of `pip install`, and run tests that require extras in an environment that has extras loaded.

Related:

- #171
