### ISSUE TITLE
Integrate notebooks into sphinx documentation (will break URLs)

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-access-kit#758]
Currently the notebooks in OAK are separate from the docs, and the user is invited to click on the ipynb file in github. This gives a decent rendering of the notebook, but it's not connected to the main docs.

Proposal

- move the notebooks folder under `docs`
- rearrange these such that the command line notebooks are in the cli folder for docs, etc
- use the nbsphinx plugin to render

An example of a project that does this is:

https://linkml.io/linkml-store/

Where there is very little hand-authored rst - all docs derived from notebooks or docstrings

Doing this will break URLs for existing notebooks (these are github URLs, don't think we can redirect)

**Comment by matentzn** [comment]
This is a great idea, I think the advantage of having noteboos and docs in one (searchable) space far outweighs the breaking URLs

**Comment by matentzn** [comment]
What about leaving a file in place with the same name and a (linked) URL to the actual notebook?
