### ISSUE TITLE
[OAK diff] Markdown output misformatted on `Mappings` section

### ISSUE THREAD

**Issue by anitacaron** [INCATools/ontology-access-kit#779]
I generated a diff between two Uberon releases, and the table in both the `Mappings added` and `Mappings removed` sections are off, so are not rendering correctly.

**Example:**
<details>
<summary>Mappings removed: 7</summary>

| Subject | Predicate | Object |
----|----|----|
| cranial nerve (UBERON:0001785)
                | oio:hasDbXref | HBA:9299 |
| vagus nerve (UBERON:0001759)
                | oio:hasDbXref | HBA:9337 |
| insect dorsal mesothorax (UBERON:6004579)
                | oio:hasDbXref | FBbt:00004579 |
| glossopharyngeal nerve (UBERON:0001649)
                | oio:hasDbXref | HBA:9334 |
| accessory XI nerve (UBERON:0002019)
                | oio:hasDbXref | HBA:9340 |
| hypoglossal nerve (UBERON:0001650)
                | oio:hasDbXref | HBA:9343 |
| trigeminal nerve (UBERON:0001645)
                | oio:hasDbXref | HBA:9322 |

</details>
------

**How the markdown table looks like:**
```md
<details>
<summary>Mappings removed: 7</summary>

| Subject | Predicate | Object |
----|----|----|
| cranial nerve (UBERON:0001785)
                | oio:hasDbXref | HBA:9299 |
| vagus nerve (UBERON:0001759)
                | oio:hasDbXref | HBA:9337 |
| insect dorsal mesothorax (UBERON:6004579)
                | oio:hasDbXref | FBbt:00004579 |
| glossopharyngeal nerve (UBERON:0001649)
                | oio:hasDbXref | HBA:9334 |
| accessory XI nerve (UBERON:0002019)
                | oio:hasDbXref | HBA:9340 |
| hypoglossal nerve (UBERON:0001650)
                | oio:hasDbXref | HBA:9343 |
| trigeminal nerve (UBERON:0001645)
                | oio:hasDbXref | HBA:9322 |

</details>
```

**Comment by hrshdhgd** [comment]
@anitacaron v0.6.11 should resolve all issues!
