### ISSUE TITLE
Docs example fails: `runoak validate -i obolibrary:mondo.obo terms`

### ISSUE THREAD

**Issue by joeflack4** [INCATools/ontology-access-kit#78]
## Description
Hello all. Glad to be finally starting to use OAK.

I'm just playing around with some options, and this first example that I took from the `README.md` didn't work.

## Error
`Error: No such option: -i`

## Log
```
runoak validate -i obolibrary:mondo.obo terms
Usage: runoak validate [OPTIONS]
Try 'runoak validate --help' for help.

Error: No such option: -i
```

**Comment by cmungall** [comment]
Thanks! I fixed the examples in the readme so the `-i` comes before the subcommand

You might find this useful:
https://incatools.github.io/ontology-access-kit/cli.html
