### ISSUE TITLE
add max depth for `vskit expand`

### ISSUE THREAD

**Issue by turbomam** [INCATools/ontology-access-kit#786]
maybe I don't want permissible values created for all of the very specific sub-classes that are eligible in the dynamic enum definition

**Comment by cmungall** [comment]
Depth is a problematic metric here

- there are different ways to calculate it. When there are multiple paths is depth the max depth, the min depth, the average? is this over is-a, all edges?
- depth/level is often a very poor proxy for specificity. See the GO FAQ entry on this https://geneontology.org/docs/faq/#ontology

Exceptions are fixed level systems like EC. 

If we add filters for depth, what about other derived statistics like information content?

I think a better methodology would be to use other OAK tools to explore the ontology to help manually curate shorelines that can be curated directly into ontologies, e.g using subsets or metaclasses.

**Comment by turbomam** [comment]
OK I'm convinced
