### ISSUE TITLE
add SubClassOf ObjectHasValue to the recognized graph projection patterns

### ISSUE THREAD

**Issue by turbomam** [INCATools/ontology-access-kit#807]
As discussed in the obo-community's ontology-access-kit thread: https://obo-communitygroup.slack.com/archives/C03D93DEALA/p1727706503549479

@cmungall did you already address this in [graph projections and subset validation #806](https://github.com/INCATools/ontology-access-kit/pull/806)?

> What OAK command can expose the fact that [MiSeq](http://purl.obolibrary.org/obo/OBI_0002003) [is_manufactured_by](http://purl.obolibrary.org/obo/OBI_0000304) [Illumina](http://purl.obolibrary.org/obo/OBI_0000759), where `Illumina` is a named individual in OBI?

see also https://ontobee.org/ontology/rdf/OBI?iri=http://purl.obolibrary.org/obo/OBI_0002003

Neither of these get it

```shell
runoak \
    --input sqlite:obo:obi relationships \
    --include-metadata .desc//p=i OBI:0400103  | grep 0000304
```

```shell
runoak \
    --input sqlite:obo:obi term-metadata \
    --output-type tsv \
    --additional-metadata .desc//p=i OBI:0400103 | grep 0000304
```

**Comment by cmungall** [comment]
Fixed in #806

**Comment by turbomam** [comment]
Awesome

```shell
runoak --input sqlite:obo:obi relationships OBI:0002003
```

> subject predicate       object  subject_label   predicate_label object_label
> OBI:0002003     rdfs:subClassOf OBI:0400103     MiSeq   None    DNA sequencer
> OBI:0002003     OBI:0000304     OBI:0000759     MiSeq   is_manufactured_by      Illumina

**Comment by turbomam** [comment]
@cmungall Now I just have to learn how to query for things that were manufactured by Illumina

**Comment by turbomam** [comment]
I can very crudely approximate what I want with

```shell
runoak --input sqlite:obo:obi relationships .all | grep is_manufactured_by | grep Illumina
```

**Comment by cmungall** [comment]
We need to enhance the docs here

Predicate abbreviations are described in the tutorial:
https://incatools.github.io/ontology-access-kit/intro/tutorial01.html#predicate-abbreviations

Predicate CURIEs always work. For common predicates (i+p), abbreviations are allowed.

We need to also mention predicate abbreviations here:
https://incatools.github.io/ontology-access-kit/howtos/use-oak-expression-language.html#ancestors
