### ISSUE TITLE
cases of `term-metadata` and `logical-definitions` failing on multiple semsql files with "curies.api.DuplicateURIPrefixes: Duplicate URI prefixes:" for CHR/chr

### ISSUE THREAD

**Issue by turbomam** [INCATools/ontology-access-kit#824]
# I will probably be closing this in an our or two. I'm using a very old version

```shell
poetry show oaklib
```

>  name         : oaklib                                                                                        
>  version      : 0.5.33

```shell
poetry show --latest oaklib
```

>  name         : oaklib                                                                                        
>  version      : 0.6.18       

```shell
poetry run runoak cache-clear
poetry run runoak --input sqlite:obo:envo term-metadata .desc//p=i 'aquatic biome'
```

> curies.api.DuplicateURIPrefixes: Duplicate URI prefixes:
> 
> http://purl.obolibrary.org/obo/CHR_:
>         prefix='CHR' uri_prefix='http://purl.obolibrary.org/obo/CHR_' prefix_synonyms=[] uri_prefix_synonyms=[] pattern=None
>         prefix='chr' uri_prefix='http://purl.obolibrary.org/obo/CHR_' prefix_synonyms=[] uri_prefix_synonyms=[] pattern=None

**Comment by turbomam** [comment]
similar thing for term-metadata of descendants in goldterms

**Comment by turbomam** [comment]
This works. Maybe it's just `term-metadata`

```shell
poetry run runoak --input sqlite:obo:envo relationships .desc//p=i 'aquatic biome'
```

**Comment by matentzn** [comment]
How was this completed? Does it work now? I still get the error..
