### ISSUE TITLE
Define internationalization_interface

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-access-kit#93]
This issue is to define internatiionalization requirements (not to implement yet)

this would have methods such as

- get_translations(curie, property)

Alternatively this could just be woven into existing interfaces. Note that all sparql impls have:

```python
    multilingual: bool = None
    preferred_language: LANGUAGE_TAG = field(default_factory=lambda: "en")
```

this is used to determine the default language if the triplestore supports multiple languages

**Comment by matentzn** [comment]
I have to implement the process that takes an ontology and a babelon profile and produces a language profile version. So:

In: 
- babelon profile with translations (rdf)
- ontology to be translated
- some config

out:
- some translated (or even multilingual) ontology.

Would oak be the right place for such a method? I would be able to figure out further requirements for internationalisation along the way.

**Comment by matentzn** [comment]
Sounds good!

**Comment by cmungall** [comment]
Was added in 0.5.0 https://github.com/INCATools/ontology-access-kit/releases/tag/v0.5.0
