### ISSUE TITLE
Lexmatch only creates skos:closeMatch?

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-access-kit#98]
Is there currently any documentation on the lexmatch code?

I noticed that currently everything in `lexmatch` get `skos:closeMatch`:

```
DOID:0050140	acute diarrhea	skos:closeMatch	SYMP:0000675	acute diarrhea	Lexical	oaklib	rdfs:label	rdfs:label	acute diarrhea
```

**Comment by cmungall** [comment]
Try running some of the tests

 - test_sssom_matcher.test_sssom_with_rules_file
 - test_cli.test_lexmatch_owl

I think this can be folded into #192 since this is a documentation deficit?

**Comment by matentzn** [comment]
@hrshdhgd I will leave it to you to fold this issue into #192 once you were able to set up the rules files in our mondo ingest ticket?

**Comment by hrshdhgd** [comment]
@matentzn , what would be the rules for mondo-ingest. The default rules.yaml in oak is [here](https://github.com/INCATools/ontology-access-kit/blob/main/tests/input/matcher_rules.yaml). As you can see there, the default is`predicate_id: skos:closeMatch`. Could this be the reason most predicates are `skos:closeMatch` @cmungall ?
